include:
  - project: opentibia-740/infra/ci-templates
    ref: main
    file:
      - /templates/defaults.yml
      - /jobs/noop.yml

variables:
  OT740_REPO_ROLE: client

test-placeholder:
  extends: .ot740_noop
