local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Be mourned pilgrim in flesh.')
npcHandler:setMessage(MESSAGE_FAREWELL, 'May enlightenment be your path.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'May enlightenment be your path.')
keywordHandler:addKeyword({'ascension'}, StdModule.say, {npcHandler = npcHandler, text = 'Godhood is at our disposal if only we throw of the shackles of mortal flesh.'})
keywordHandler:addKeyword({'mourn'}, StdModule.say, {npcHandler = npcHandler, text = 'We are mortals and thus miserable creatures that are to be mourned.'})
keywordHandler:addKeyword({'oldpharaoh'}, StdModule.say, {npcHandler = npcHandler, text = 'The foolish old pharaoh withheld knowledge and power from his son, knowing that he would surpass him in every aspects. But his son granted him the chance to ascend.'})
keywordHandler:addKeyword({'darashia'}, StdModule.say, {npcHandler = npcHandler, text = 'The foolishness of their ways will eventually spell their doom.'})
keywordHandler:addKeyword({'daraman'}, StdModule.say, {npcHandler = npcHandler, text = 'He was close to the truth, but he lacked the wisdom and vision of our pharaoh.'})
keywordHandler:addKeyword({'ankrahmun'}, StdModule.say, {npcHandler = npcHandler, text = 'Our city will endure the sands of the desert and the grinding teeth of time.'})
keywordHandler:addKeyword({'temple'}, StdModule.say, {npcHandler = npcHandler, text = 'The temple is a school for us mourned mortals. The teachings of the temple help us to find our way through our mortal days.'})
keywordHandler:addKeyword({'palace'}, StdModule.say, {npcHandler = npcHandler, text = 'The palace is the home of our beloved pharaoh.'})
keywordHandler:addKeyword({'kazordoon'}, StdModule.say, {npcHandler = npcHandler, text = 'We rarely see a traveler of the small folk here.'})
keywordHandler:addKeyword({'darama'}, StdModule.say, {npcHandler = npcHandler, text = 'Life here is harsh, but only this way can we deny the temptations that might damage our Rah and our Uthun to our traitorous flesh.'})
keywordHandler:addKeyword({'Rah'}, StdModule.say, {npcHandler = npcHandler, text = 'The Rah could be called our soul.'})
keywordHandler:addKeyword({'pharaoh'}, StdModule.say, {npcHandler = npcHandler, text = 'Our pharaoh holds the key to our ascension. Praised be our pharaoh.'})
keywordHandler:addKeyword({'Akh'}, StdModule.say, {npcHandler = npcHandler, text = 'Your cursed bodys are called the Akh. As long as we are alive the Akh makes us weak and vulnerable.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'The world is nothing but a sigil of death, a monument of decay. We have to attune to death to become one with the world.'})
keywordHandler:addKeyword({'light'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell torches, candlesticks, candelabra, and oil.'})
keywordHandler:addKeyword({'scarab'}, StdModule.say, {npcHandler = npcHandler, text = 'The eternal burrowers are the keepers of all the secrets their kind has unearthed in countless aeons.'})
keywordHandler:addKeyword({'chosen'}, StdModule.say, {npcHandler = npcHandler, text = 'Only the most worthy and pious are chosen to join the armies of the pharaoh. In undeath they follow the path of ascension.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'It were foolish of me to tell you the time, because then you won\'t buy a watch.'})
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'The vain cities of the Tibian continent think they are at the centre of the universe. Little do they know about the wisdom of the pharaoh.'})
keywordHandler:addKeyword({'undead'}, StdModule.say, {npcHandler = npcHandler, text = 'Undeath is the path to ascension which the chosen may follow.'})
keywordHandler:addKeyword({'uthun'}, StdModule.say, {npcHandler = npcHandler, text = 'The Uthun is that what we learn and remember.'})
keywordHandler:addKeyword({'arena'}, StdModule.say, {npcHandler = npcHandler, text = 'The arena is east of here.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell equipment of all sorts.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the mourned Ahmet.'})
keywordHandler:addKeyword({'mortality'}, StdModule.say, {npcHandler = npcHandler, text = 'Mortality is our curse. Mourned shall we be.'})
keywordHandler:addKeyword({'worm'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell worms only in sixpacks for 5 gold each, how many sixpacks of worms do you want to buy?'})
keywordHandler:addKeyword({'equipment'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell shovels, picks, scythes, bags, ropes, backpacks, plates, cups, scrolls, documents, parchments, lightsources and watches. Of course, I sell fishing rods and six-packs of worms, too.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'bag'}, 2863, 4, 'bag')
shopModule:addBuyableItem({'crowbar'}, 3304, 260, 'crowbar')
shopModule:addBuyableItem({'rod'}, 3483, 150, 'rod')
shopModule:addBuyableItem({'present'}, 2856, 10, 'present')
shopModule:addBuyableItem({'shovel'}, 3457, 10, 'shovel')
shopModule:addBuyableItem({'bottle'}, 2875, 3, 'bottle')
shopModule:addBuyableItem({'watch'}, 2906, 20, 'watch')
shopModule:addBuyableItem({'torch'}, 2920, 2, 'torch')
shopModule:addBuyableItem({'oil'}, 2874, 20, 'oil')
shopModule:addBuyableItem({'candlestick'}, 2917, 2, 'candlestick')
shopModule:addBuyableItem({'scroll'}, 2815, 5, 'scroll')
shopModule:addBuyableItem({'water'}, 2901, 40, 'water')
shopModule:addBuyableItem({'scythe'}, 3453, 50, 'scythe')
shopModule:addBuyableItem({'pick'}, 3456, 50, 'pick')
shopModule:addBuyableItem({'document'}, 2834, 12, 'document')
shopModule:addBuyableItem({'bucket'}, 2873, 4, 'bucket')
shopModule:addBuyableItem({'backpack'}, 2871, 10, 'backpack')
shopModule:addBuyableItem({'rope'}, 3003, 50, 'rope')
shopModule:addBuyableItem({'parchment'}, 2835, 8, 'parchment')
shopModule:addBuyableItem({'cup'}, 2881, 2, 'cup')
shopModule:addBuyableItem({'candelabr'}, 2911, 8, 'candelabr')
shopModule:addBuyableItem({'plate'}, 2905, 6, 'plate')
shopModule:addSellableItem({'sell'}, 3003, 8, 'sell')

npcHandler:addModule(FocusModule:new())

