local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'I welcome you, |PLAYERNAME|!')
npcHandler:setMessage(MESSAGE_FAREWELL, 'May your path be as straight as an arrow.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'May your path be as straight as an arrow.')
keywordHandler:addKeyword({'thanks'}, StdModule.say, {npcHandler = npcHandler, text = 'I hope you learned something.'})
keywordHandler:addKeyword({'rage'}, StdModule.say, {npcHandler = npcHandler, text = 'Rage is the legacy of Blog, the beast. To overcome it is our primal goal. The Mooh\'Tah is our only hope of salvation and perfection.'})
keywordHandler:addKeyword({'weapon'}, StdModule.say, {npcHandler = npcHandler, text = 'Make your will your weapon, and your enemies will perish.'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'I offer you the teachings of knighthood and the way of the paladin.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'To rely on magic is like to cheat fate. All cheaters will find their just punishment one day, and so will he.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'Focus on your own life, not on that of others.'})
keywordHandler:addKeyword({'sing'}, StdModule.say, {npcHandler = npcHandler, text = 'Each harmonic action has it own song. If you can sing it, you are in harmony with that action. This is where the minotaurean battlesongs come from.'})
keywordHandler:addKeyword({'armor'}, StdModule.say, {npcHandler = npcHandler, text = 'Courage is the only armor that shields you against rage and fear, the greatest dangers you will have to face.'})
keywordHandler:addKeyword({'harmony'}, StdModule.say, {npcHandler = npcHandler, text = 'There is an elegant harmony in every thing done right. If you feel the harmony of an action you can sing its song.'})
keywordHandler:addKeyword({'gods'}, StdModule.say, {npcHandler = npcHandler, text = 'By them we were imbued with the rage that almost costed our existence. By them we were used as pawns in wars that were not ours.'})
keywordHandler:addKeyword({'monster'}, StdModule.say, {npcHandler = npcHandler, text = 'Inferior creatures of rage, driven by their primitive urges. Only worthy to be noticed to test one\'s skills.'})
keywordHandler:addKeyword({'guidance'}, StdModule.say, {npcHandler = npcHandler, text = 'Like all true minotaurean blademasters I am a warrior-philosopher of the Mooh\'Tah.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'If it\'s truly a weapon to slay gods it might be worth to be sought for.'})
keywordHandler:addKeyword({'venore'}, StdModule.say, {npcHandler = npcHandler, text = 'The city pays me well and those undisciplined gladiators need my skills and guidance badly.'})
keywordHandler:addKeyword({'gladiator'}, StdModule.say, {npcHandler = npcHandler, text = 'Those wannabe fighters are weak and most of them are unable to comprehend a higher concept like the Mooh\'Tah.'})
keywordHandler:addKeyword({'spell'}, StdModule.say, {npcHandler = npcHandler, text = 'Sorry, I only teach spells to knights and paladins.'})
keywordHandler:addKeyword({'minotaur'}, StdModule.say, {npcHandler = npcHandler, text = 'In the ancient wars we lost much because of the rage. The one good thing is we lost our trust in the gods, too.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'I pledge no allegiance to any king, be it human or minotaurean.'})
keywordHandler:addKeyword({'shield'}, StdModule.say, {npcHandler = npcHandler, text = 'Your confidence shall be your shield. Nothing can penetrate that defence. No emotion will let you lose your focus.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'Your human army might be big, but without skills. They are only sheep to be slaughtered.'})
keywordHandler:addKeyword({'general'}, StdModule.say, {npcHandler = npcHandler, text = 'Your human generals are like their warriors. They lack the focus to be a true warrior.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'It is the current time.'})
keywordHandler:addKeyword({'battlesongs'}, StdModule.say, {npcHandler = npcHandler, text = 'Each Mooh\'Tah master focuses his skills on the harmony of battle. He is one with the song that he\'s singing with his voice or at least his heart.'})
keywordHandler:addKeyword({'help'}, StdModule.say, {npcHandler = npcHandler, text = 'I teach worthy warriors the way of the knight.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the overseer of the pits and the trainer of the gladiators.'})
keywordHandler:addKeyword({'mintwallin'}, StdModule.say, {npcHandler = npcHandler, text = 'The city is only a shadow of what we could have accomplished without that curse of rage that the gods bestowed upon us.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am known as Asrak the Ironhoof.'})
keywordHandler:addKeyword({'dungeon'}, StdModule.say, {npcHandler = npcHandler, text = 'The dungeons of your desires and fears are the only ones you really should fear and those you really have to conquer.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)

npcHandler:addModule(FocusModule:new())

