local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Hello, hiho, and ashari |PLAYERNAME|.')
npcHandler:setMessage(MESSAGE_FAREWELL, 'See you later.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'See you later.')
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'Though they rebelled against our king it\'s said that the city is very lovely.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'My job is to sell all kind of useful equipment.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am called Beatrice.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s the current time right now.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'I supply them with some basic stuff.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'I have seen him once. What a handsome man he is.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'I vaguely remember that name.'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'My inventory is large, just have a look at the blackboard.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'I don\'t like travelling much. I prefer to live in the safety of our city.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'There are always rumors about the dangers in the far north of Edron.'})
keywordHandler:addKeyword({'thais'}, StdModule.say, {npcHandler = npcHandler, text = 'We are no longer in need to be supplied from there.'})
keywordHandler:addKeyword({'worm'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell worms only in sixpacks for 5 gold each, how many sixpacks of worms do you want to buy?'})
keywordHandler:addKeyword({'edron'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s the best place to live at.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'A myth like the screwdriver of Kurik or the endless vial of manafluid.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'watch'}, 2906, 20, 'watch')
shopModule:addBuyableItem({'crowbar'}, 3304, 260, 'crowbar')
shopModule:addBuyableItem({'pick'}, 3456, 50, 'pick')
shopModule:addBuyableItem({'lamp'}, 2914, 8, 'lamp')
shopModule:addBuyableItem({'basket'}, 2855, 6, 'basket')
shopModule:addBuyableItem({'trap'}, 3481, 280, 'trap')
shopModule:addBuyableItem({'rod'}, 3483, 150, 'rod')
shopModule:addBuyableItem({'backpack'}, 2869, 20, 'backpack')
shopModule:addBuyableItem({'football'}, 2990, 111, 'football')
shopModule:addBuyableItem({'bag'}, 2861, 5, 'bag')
shopModule:addBuyableItem({'scythe'}, 3453, 50, 'scythe')
shopModule:addBuyableItem({'rope'}, 3003, 50, 'rope')
shopModule:addBuyableItem({'bucket'}, 2873, 4, 'bucket')
shopModule:addBuyableItem({'torch'}, 2920, 2, 'torch')
shopModule:addBuyableItem({'shovel'}, 3457, 50, 'shovel')
shopModule:addBuyableItem({'candlestick'}, 2917, 2, 'candlestick')
shopModule:addSellableItem({'sell'}, 3293, 3, 'sell')
shopModule:addSellableItem({'sell'}, 2906, 6, 'sell')
shopModule:addSellableItem({'sell'}, 3509, 8, 'sell')
shopModule:addSellableItem({'sell'}, 3453, 12, 'sell')
shopModule:addSellableItem({'sell'}, 3456, 15, 'sell')
shopModule:addSellableItem({'sell'}, 3304, 50, 'sell')
shopModule:addSellableItem({'sell'}, 3483, 40, 'sell')
shopModule:addSellableItem({'sell'}, 3457, 8, 'sell')
shopModule:addSellableItem({'sell'}, 3003, 15, 'sell')
shopModule:addSellableItem({'sell'}, 3463, 10, 'sell')
shopModule:addSellableItem({'sell'}, 3481, 75, 'sell')

npcHandler:addModule(FocusModule:new())

