local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Ah, looking for some cooking gear today, |PLAYERNAME|?')
npcHandler:setMessage(MESSAGE_FAREWELL, 'So long, |PLAYERNAME|.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'So long, |PLAYERNAME|.')
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Watches are sold in the south east part of this warehouse.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell all the cooking gear you can dream of.'})
keywordHandler:addKeyword({'gambling'}, StdModule.say, {npcHandler = npcHandler, text = 'Thanks to that taxes I have not enough spare money to gamble much.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am Chephan, at your service.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'They brought most of their cooking gear from thais.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'Even a king needs a fork now and then. To scratch his back or to poke servants for example.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'See this fork? Now imagine what a hero like you could do to an evil sorcerer with that fork! Care to buy one?'})
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'So many women and so little intrest in cooking, horrible.'})
keywordHandler:addKeyword({'warehouse'}, StdModule.say, {npcHandler = npcHandler, text = 'Here you can by so many things you will need one day or another. Just have a look.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'The world is flat as this plate. You should buy one as a symbol for Tibia.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'My recipies are family secrets, sorry.'})
keywordHandler:addKeyword({'privilege'}, StdModule.say, {npcHandler = npcHandler, text = 'I don\'t feel that privileged. In fact our beloved city is bleeding for the profit of Thais.'})
keywordHandler:addKeyword({'thais'}, StdModule.say, {npcHandler = npcHandler, text = 'Thaian cooking gear is of inferior quality. Make sure to upgrade yours here as soon as you can.'})
keywordHandler:addKeyword({'tax'}, StdModule.say, {npcHandler = npcHandler, text = 'Those taxes are killing me. And they are getting worse each year!'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'That would be: Buckets, bottles, mugs, cups, jugs, plates, baking trays, pots, pans, forks, spoons, knifes, wooden spoons, cleavers, spatulas, and rolling pins.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'Just an oversized kitchenknife. Better buy the real thing.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'jug'}, 2882, 10, 'jug')
shopModule:addBuyableItem({'spoon'}, 3468, 10, 'spoon')
shopModule:addBuyableItem({'bottle'}, 2875, 3, 'bottle')
shopModule:addBuyableItem({'fork'}, 3467, 10, 'fork')
shopModule:addBuyableItem({'pot'}, 3465, 30, 'pot')
shopModule:addBuyableItem({'spatula'}, 3472, 12, 'spatula')
shopModule:addBuyableItem({'wooden'}, 3470, 5, 'wooden')
shopModule:addBuyableItem({'baking'}, 3464, 20, 'baking')
shopModule:addBuyableItem({'bucket'}, 2873, 4, 'bucket')
shopModule:addBuyableItem({'mug'}, 2880, 4, 'mug')
shopModule:addBuyableItem({'rolling'}, 3473, 12, 'rolling')
shopModule:addBuyableItem({'cleaver'}, 3471, 15, 'cleaver')
shopModule:addBuyableItem({'pan'}, 3466, 20, 'pan')
shopModule:addBuyableItem({'cup'}, 2881, 2, 'cup')
shopModule:addBuyableItem({'knife'}, 3469, 10, 'knife')
shopModule:addBuyableItem({'plate'}, 2905, 6, 'plate')

npcHandler:addModule(FocusModule:new())

