local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Salutations, stranger.')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Take care out there!')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Take care out there!')
keywordHandler:addKeyword({'castle'}, StdModule.say, {npcHandler = npcHandler, text = 'The castle isn\'t safe! I warned them of the entrance to the dungeons, but no one is litstening. How many people have to die before they do something about that?'})
keywordHandler:addKeyword({'stutch'}, StdModule.say, {npcHandler = npcHandler, text = 'He is one of the few people I can trust.'})
keywordHandler:addKeyword({'truth'}, StdModule.say, {npcHandler = npcHandler, text = 'The dungeons are full of hideous monsters, unnamed terrors, unsolved riddles ... and maybe some answers. Believe me! The truth is down there ... somewhere!'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'Some say he\'s the avatar of Zathroth himself, but perhaps the truth about him is even darker then the worst rumours can imagine.'})
keywordHandler:addKeyword({'fiend'}, StdModule.say, {npcHandler = npcHandler, text = 'Not everything that walks our streets is human ... or even living.'})
keywordHandler:addKeyword({'sorcerer'}, StdModule.say, {npcHandler = npcHandler, text = 'I don\'t know where they got their secret spells in the first place, nor did most of them know ... If I were a sorcerer that would be a fact to give me nightmares.'})
keywordHandler:addKeyword({'knight'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s too easy to become a knight. They take almost everyone. And if you look in the streets you can see what happens if you give training and a flashy title to almost everyone.'})
keywordHandler:addKeyword({'aruda'}, StdModule.say, {npcHandler = npcHandler, text = 'This woman is a clever thief, so watch out when you are talking to her.'})
keywordHandler:addKeyword({'sell'}, StdModule.say, {npcHandler = npcHandler, text = 'I am no tradesman, sorry.'})
keywordHandler:addKeyword({'trust'}, StdModule.say, {npcHandler = npcHandler, text = 'Too many possibilities to become a servant of darkness to trust ANYONE!'})
keywordHandler:addKeyword({'sam'}, StdModule.say, {npcHandler = npcHandler, text = 'I say it was a mistake to rely on a single person for such vital services but having those venoreans here is even worse.'})
keywordHandler:addKeyword({'frodo'}, StdModule.say, {npcHandler = npcHandler, text = 'Have you noticed how easy it would be to poison his supplies and kill a great deal of people with ease?'})
keywordHandler:addKeyword({'report'}, StdModule.say, {npcHandler = npcHandler, text = 'My reports are confidential and for the ears and eyes of the king only.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'King Tibianus III is our leader and my direct superior.'})
keywordHandler:addKeyword({'benjamin'}, StdModule.say, {npcHandler = npcHandler, text = 'Something happened to him that snapped his mind. Can we be sure what more might have happened to him unnoticed?'})
keywordHandler:addKeyword({'city'}, StdModule.say, {npcHandler = npcHandler, text = 'The city is open to almost everyone. That literally opens doors for all kinds of criminals and fiends.'})
keywordHandler:addKeyword({'dungeon'}, StdModule.say, {npcHandler = npcHandler, text = 'Monsters lurk in each corner of the dungeons, which spread beneath us, breeding in the shadows and plotting to destroy us all.'})
keywordHandler:addKeyword({'gods'}, StdModule.say, {npcHandler = npcHandler, text = 'We are just the pawns of the gods. The best we can expect is that our play amuses them enough to keep their interest in us so we might live a day or two longer.'})
keywordHandler:addKeyword({'mcronald'}, StdModule.say, {npcHandler = npcHandler, text = 'Have you ever wondered what these caves under their farm are good for? And have you noticed how many adventurers go down there and never return? Well, think about it!'})
keywordHandler:addKeyword({'incident'}, StdModule.say, {npcHandler = npcHandler, text = 'There are things that must be kept secret.'})
keywordHandler:addKeyword({'gorn'}, StdModule.say, {npcHandler = npcHandler, text = 'A man too concerned about profit to be trustworthy. This kind of man sells his soul to the highest bidder. It\'s just a question if he has done it already or will do it soon.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'We are surrounded by myths, living and dead. How can someone doubt that there IS something like Excalibug somewhere?'})
keywordHandler:addKeyword({'criminal'}, StdModule.say, {npcHandler = npcHandler, text = 'There are so many murderers and thiefs out there that I wonder if there is some greater force of evil subtly encouraging that.'})
keywordHandler:addKeyword({'lugri'}, StdModule.say, {npcHandler = npcHandler, text = 'At least you KNOW that you have to expect only evilness from this guy and that\'s the best one can say about him.'})
keywordHandler:addKeyword({'secret'}, StdModule.say, {npcHandler = npcHandler, text = 'Certain information is not for the eyes and ears of everyone. Please understand that.'})
keywordHandler:addKeyword({'spies'}, StdModule.say, {npcHandler = npcHandler, text = 'Polymorphed Minotaurs, shapechanging demons, possessed innocents ... who can tell for sure.'})
keywordHandler:addKeyword({'superior'}, StdModule.say, {npcHandler = npcHandler, text = 'I report directly to the king himself.'})
keywordHandler:addKeyword({'paladin'}, StdModule.say, {npcHandler = npcHandler, text = 'They should be noble warriors, but does it take bravery to shoot someone from a certain distance? The former paladins were virtuous heroes, the ones you meet today are just simple treasure hunters.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'Our army might be infested with spies already.'})
keywordHandler:addKeyword({'partos'}, StdModule.say, {npcHandler = npcHandler, text = 'This criminal was wanted for many crimes. At last he got caught and put to jail.'})
keywordHandler:addKeyword({'quentin'}, StdModule.say, {npcHandler = npcHandler, text = 'A peaceful man. But in our days peace is just an illusion. We are surrounded by enemies and dangers.'})
keywordHandler:addKeyword({'guard'}, StdModule.say, {npcHandler = npcHandler, text = 'I think we can\'t trust the guards anymore.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the head of the TBI.'})
keywordHandler:addKeyword({'citizen'}, StdModule.say, {npcHandler = npcHandler, text = 'I only can give you some official information about our citizens. About whom do you wish to talk?'})
keywordHandler:addKeyword({'investigation'}, StdModule.say, {npcHandler = npcHandler, text = 'We collect information about people and incidents.'})
keywordHandler:addKeyword({'enemy'}, StdModule.say, {npcHandler = npcHandler, text = 'The people of the northern city, the minotaurs, the followers of Zathroth, the demons, and countless others!'})
keywordHandler:addKeyword({'druid'}, StdModule.say, {npcHandler = npcHandler, text = 'It is said that druids are preservers of life and good aligned, but let me ask you if it\'s so \'good\' to sell runes to the highest bidder, no matter who that might be? I think you get the point!'})
keywordHandler:addKeyword({'lynda'}, StdModule.say, {npcHandler = npcHandler, text = 'She puts her trust in the help of beings she can\'t comprehend. Think by yourself if that\'s clever.'})
keywordHandler:addKeyword({'bozo'}, StdModule.say, {npcHandler = npcHandler, text = 'He isn\'t the fool he pretends to be. So to what is he up to?'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'Sorry, almost news that are a little interesting are confidential.'})
keywordHandler:addKeyword({'berfasmur'}, StdModule.say, {npcHandler = npcHandler, text = 'Strange name, isn\'t it? Play around with the letters and you are in for a surprise.'})
keywordHandler:addKeyword({'demon'}, StdModule.say, {npcHandler = npcHandler, text = 'They say there are just two of them in the underground ruins! These damned fools! There are dozens of them! And the two they already saw are only some of the weakest of demonkind!'})
keywordHandler:addKeyword({'rebellion'}, StdModule.say, {npcHandler = npcHandler, text = 'I have far too few information about the rebellion, but we suspect the followers of Zathroth behind it.'})
keywordHandler:addKeyword({'danger'}, StdModule.say, {npcHandler = npcHandler, text = 'Danger is common like day and night for a Tibian, who keeps his eyes open.'})
keywordHandler:addKeyword({'people'}, StdModule.say, {npcHandler = npcHandler, text = 'We know much about the citizens and some other people.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)

npcHandler:addModule(FocusModule:new())

