local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Be greeted |PLAYERNAME|.')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Asha Thrazi, stranger.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Asha Thrazi, stranger.')
keywordHandler:addKeyword({'humans'}, StdModule.say, {npcHandler = npcHandler, text = 'They are useful ... and better stay useful.'})
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'We watch this city and the actions of its inhabitants closely.'})
keywordHandler:addKeyword({'hellgate'}, StdModule.say, {npcHandler = npcHandler, text = 'It was here among other structures, like the depot tower, before our people came here. It\'s secured by a sealed door.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'News are confidential and not your business.'})
keywordHandler:addKeyword({'troll'}, StdModule.say, {npcHandler = npcHandler, text = 'Like all inferior races they can be at least used for something good. The other castes are just jealous about our use of them.'})
keywordHandler:addKeyword({'olrik'}, StdModule.say, {npcHandler = npcHandler, text = 'This human is too unimportant to be even mentioned.'})
keywordHandler:addKeyword({'sorcerer'}, StdModule.say, {npcHandler = npcHandler, text = 'I have seen human sorcerers doing some impressive things ... before they died.'})
keywordHandler:addKeyword({'dwarfs'}, StdModule.say, {npcHandler = npcHandler, text = 'We might use the shelter earth and hills provide us, but their obsession for metal is a waste of time.'})
keywordHandler:addKeyword({'tibianus'}, StdModule.say, {npcHandler = npcHandler, text = 'A human weakling, not much more.'})
keywordHandler:addKeyword({'druid'}, StdModule.say, {npcHandler = npcHandler, text = 'Druids\' magic is too peaceful for my taste.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s hard for some of my people to grasp the true concept of a strong leader.'})
keywordHandler:addKeyword({'cenath'}, StdModule.say, {npcHandler = npcHandler, text = 'Arrogant bastards, but they wield quite powerful magics.'})
keywordHandler:addKeyword({'spell'}, StdModule.say, {npcHandler = npcHandler, text = 'I teach the spells \'Light Magic Missile\', \'Heavy Magic Missile\', \'Fireball\', \'Great Fireball\', \'Fire Bomb\', and \'Explosion\'.'})
keywordHandler:addKeyword({'venore'}, StdModule.say, {npcHandler = npcHandler, text = 'The merchants of venore provide us with some usefull goods. Still I an convinced that they get more out of our bargain then we do.'})
keywordHandler:addKeyword({'sheriff'}, StdModule.say, {npcHandler = npcHandler, text = 'Sometimes people get imprisoned for some time. True criminals will be cast out and for comitting the worst crimes offenders are thrown into the hellgate.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'I still doubt it exists.'})
keywordHandler:addKeyword({'elves'}, StdModule.say, {npcHandler = npcHandler, text = 'My people are divided in castes in these times, until they comprehend that only the way of the Kuridai can save us all.'})
keywordHandler:addKeyword({'door'}, StdModule.say, {npcHandler = npcHandler, text = 'For safety we keep the door to the hellgate locked all times. I have the keys to open it when needed.'})
keywordHandler:addKeyword({'roderick'}, StdModule.say, {npcHandler = npcHandler, text = 'He is tolerated here as the spokesman of the thaian king.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s one of the more useful concepts we can learn from the other races.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'I couldn\'t care less.'})
keywordHandler:addKeyword({'mortiur'}, StdModule.say, {npcHandler = npcHandler, text = 'The celestial paladin of revenge. He was one of the greatest elven wariors of all times.'})
keywordHandler:addKeyword({'magic'}, StdModule.say, {npcHandler = npcHandler, text = 'I mastered some spells of battle.'})
keywordHandler:addKeyword({'abdaisim'}, StdModule.say, {npcHandler = npcHandler, text = 'Even more undecided then the deraisim.'})
keywordHandler:addKeyword({'teshial'}, StdModule.say, {npcHandler = npcHandler, text = 'Dreamers are of no practical use. I don\'t mourn their demise.'})
keywordHandler:addKeyword({'thais'}, StdModule.say, {npcHandler = npcHandler, text = 'The thain kingdom and we share some enemys, so its only logical to cooperate in a few areas.'})
keywordHandler:addKeyword({'kuridai'}, StdModule.say, {npcHandler = npcHandler, text = 'We are the heart of the elven society. We forge, we build, and we don\'t allow our people to be pushed around.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the leader of the Kuridai and the Az\'irel of Ab\'dendriel. Humans would call it sheriff, executioner, or avenger.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'Even if he\'d walk through the town above the other castes won\'t see the necessity to follow OUR way.'})
keywordHandler:addKeyword({'crunor'}, StdModule.say, {npcHandler = npcHandler, text = 'I have no use for the treething. I worship Mortiur, the ravager, of course.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'Not that I like to talk to you, but I am Elathriel Shadowslayer.'})
keywordHandler:addKeyword({'deraisim'}, StdModule.say, {npcHandler = npcHandler, text = 'Confused cowards. With all their skill they still tend to hide and run. What a waste.'})
keywordHandler:addKeyword({'spellbook'}, StdModule.say, {npcHandler = npcHandler, text = 'I don\'t sell such stuff.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'key'}, 2970, 5000, 'key')

npcHandler:addModule(FocusModule:new())

