local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Welcome to Frodo\'s Hut. You heard about the news?')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Please come back from time to time.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Please come back from time to time.')
keywordHandler:addKeyword({'sherry'}, StdModule.say, {npcHandler = npcHandler, text = 'The McRonalds are a nice couple. Donald is a dear friend of mine.'})
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'Many travellers tell funny stories about all the emancipated women in this northern town.'})
keywordHandler:addKeyword({'hugo'}, StdModule.say, {npcHandler = npcHandler, text = 'I think some time ago a stranger from Fibula with that name stayed here for some nights.'})
keywordHandler:addKeyword({'gregor'}, StdModule.say, {npcHandler = npcHandler, text = 'The knights have sometimes parties here after some arena fights.'})
keywordHandler:addKeyword({'riddle'}, StdModule.say, {npcHandler = npcHandler, text = 'I heard it when I was a child.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'Uhm, do not mention him. It may scare customers away.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'Some travelers from Edron told about a great treasure guarded by cruel demons in the dungeons there.'})
keywordHandler:addKeyword({'berfasmur'}, StdModule.say, {npcHandler = npcHandler, text = 'Sorry, he spoke only very little. I know nothing more about him.'})
keywordHandler:addKeyword({'xodet'}, StdModule.say, {npcHandler = npcHandler, text = 'I don\'t know where he gets these fluids. If I could sell them here, the hut would be crowded.'})
keywordHandler:addKeyword({'galuna'}, StdModule.say, {npcHandler = npcHandler, text = 'She makes excellent arrows and bows.'})
keywordHandler:addKeyword({'satanic'}, StdModule.say, {npcHandler = npcHandler, text = 'Hmm, I have heard of a \'satanic influence\' theory by someone called Newton or something like that... Maybe there\'s more in the Royal Archives.'})
keywordHandler:addKeyword({'muriel'}, StdModule.say, {npcHandler = npcHandler, text = 'Muriel has never visited this place.'})
keywordHandler:addKeyword({'marvik'}, StdModule.say, {npcHandler = npcHandler, text = 'Marvik seldom leaves his guildhall at all.'})
keywordHandler:addKeyword({'oswald'}, StdModule.say, {npcHandler = npcHandler, text = 'I hate him. Each of his visits here ends with a bar brawl.'})
keywordHandler:addKeyword({'sam'}, StdModule.say, {npcHandler = npcHandler, text = 'A loud neighbour, I get a lot of complaints about him.'})
keywordHandler:addKeyword({'todd'}, StdModule.say, {npcHandler = npcHandler, text = 'That fellow is filthy rich. He rented a room upstairs for months in advance and always orders the best beer and wine i serve.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'Oh, our beloved king! Thanks to him, alcohol is so cheap.'})
keywordHandler:addKeyword({'buy'}, StdModule.say, {npcHandler = npcHandler, text = 'I can offer you bread, cheese, ham, or meat.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'Nothing more than a tale for warriors.'})
keywordHandler:addKeyword({'thais'}, StdModule.say, {npcHandler = npcHandler, text = 'Here in Thais is the center of Tibia.'})
keywordHandler:addKeyword({'gorn'}, StdModule.say, {npcHandler = npcHandler, text = 'Many of his customers visit my Hut, too.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'Come on! You know that our world is called Tibia.'})
keywordHandler:addKeyword({'lugri'}, StdModule.say, {npcHandler = npcHandler, text = 'I overheared some conversations about his evilness. That\'s enough to hope, that I never ever meet him.'})
keywordHandler:addKeyword({'dungeon'}, StdModule.say, {npcHandler = npcHandler, text = 'Ah yes, the graveyard dungeon. All I know is this riddle: His Grave to the south, the tree above, his soul in the shade. No idea what that means, though!'})
keywordHandler:addKeyword({'archives'}, StdModule.say, {npcHandler = npcHandler, text = 'Oh, the Royal Archives are in Rain Castle!'})
keywordHandler:addKeyword({'elane'}, StdModule.say, {npcHandler = npcHandler, text = 'Can you believe that she actually told her guildfellows that alcohol is a bad thing?'})
keywordHandler:addKeyword({'food'}, StdModule.say, {npcHandler = npcHandler, text = 'Are you looking for food? I have bread, cheese, ham, and meat.'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'Hehe. Great customers.'})
keywordHandler:addKeyword({'general'}, StdModule.say, {npcHandler = npcHandler, text = 'Harkath Bloodblade is the royal general.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'It is exactly the current time.'})
keywordHandler:addKeyword({'quentin'}, StdModule.say, {npcHandler = npcHandler, text = 'He hardly visits my humble tavern.'})
keywordHandler:addKeyword({'harkath'}, StdModule.say, {npcHandler = npcHandler, text = 'Too disciplined to enjoy life.'})
keywordHandler:addKeyword({'lungelen'}, StdModule.say, {npcHandler = npcHandler, text = 'A sorceress, you can find her in their guild sitting befor a book - always!'})
keywordHandler:addKeyword({'baxter'}, StdModule.say, {npcHandler = npcHandler, text = 'He\'s able to drink a bottle or two.'})
keywordHandler:addKeyword({'bozo'}, StdModule.say, {npcHandler = npcHandler, text = 'I am trying to hire him for an evening or two.'})
keywordHandler:addKeyword({'donald'}, StdModule.say, {npcHandler = npcHandler, text = 'He is a little shy. In his youth he dreamed to become a druid.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the owner of this saloon. I call it Frodo\'s Hut. I am also selling food.'})
keywordHandler:addKeyword({'cropwell'}, StdModule.say, {npcHandler = npcHandler, text = 'No idea who that is, but maybe you\'ll find something in the Royal Archives...'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'Just call me Frodo.'})
keywordHandler:addKeyword({'hut'}, StdModule.say, {npcHandler = npcHandler, text = 'I hope you like it.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'ham'}, 3582, 8, 'ham')
shopModule:addBuyableItem({'meat'}, 3577, 5, 'meat')
shopModule:addBuyableItem({'cheese'}, 3607, 6, 'cheese')
shopModule:addBuyableItem({'bread'}, 3600, 4, 'bread')

npcHandler:addModule(FocusModule:new())

