local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_FAREWELL, 'You\'ll come back. They all do.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'You\'ll come back. They all do.')
keywordHandler:addKeyword({'castle'}, StdModule.say, {npcHandler = npcHandler, text = 'I\'ve said it a thousand times! That place needs a complete refurbishing!'})
keywordHandler:addKeyword({'gregor'}, StdModule.say, {npcHandler = npcHandler, text = 'Those knights know how to party. And after such partys theres allways need for new furniture.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'You mean my specials, don\'t you?'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'My friends call me Gamon. My fans call me the incredible Gammy!'})
keywordHandler:addKeyword({'muriel'}, StdModule.say, {npcHandler = npcHandler, text = 'The sorcerers guild could realy need someone with taste to redecorate it.'})
keywordHandler:addKeyword({'marvik'}, StdModule.say, {npcHandler = npcHandler, text = 'Druids are obsessed with trees and the bane of any carpenter.'})
keywordHandler:addKeyword({'sam'}, StdModule.say, {npcHandler = npcHandler, text = 'I heard rumours he has some special offers for customers who know to ask for the correct things.'})
keywordHandler:addKeyword({'benjamin'}, StdModule.say, {npcHandler = npcHandler, text = 'He\'s incredibly slow. Just your average postman, I guess.'})
keywordHandler:addKeyword({'watching'}, StdModule.say, {npcHandler = npcHandler, text = 'Look! They are doing it again! And they are always smiling!'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell statues, tables, chairs, flowers, pillows, pottery, instruments, decoration, tapestries and containers.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'His Royal Highness will start to appreciate the superior quality of our stock soon enough!'})
keywordHandler:addKeyword({'smiling'}, StdModule.say, {npcHandler = npcHandler, text = 'Yes! Smiling! How a professional sales artist such as myself is supposed to work in such an atmosphere is beyond me!'})
keywordHandler:addKeyword({'Venore'}, StdModule.say, {npcHandler = npcHandler, text = 'The place where it all happens. That town really rocks! Thais could learn a lot about interior decoration from Venore!'})
keywordHandler:addKeyword({'Thais'}, StdModule.say, {npcHandler = npcHandler, text = 'Thais is obsessed with its past. Everybody here is so proud of their history. Bah! Thais might have a long history, but it has no idea when it comes to interior decoration.'})
keywordHandler:addKeyword({'gorn'}, StdModule.say, {npcHandler = npcHandler, text = 'He sells stuff of inferior quality. Nothing compared to venores high quality goods.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'Tibia is a wonderful place full of business opportunities.'})
keywordHandler:addKeyword({'rug'}, StdModule.say, {npcHandler = npcHandler, text = 'Oh, silly me! Rugs are out of stock at the moment! But we expect a new shipment anytime. Just watch out for the next update!... Of our inventory I mean.'})
keywordHandler:addKeyword({'elane'}, StdModule.say, {npcHandler = npcHandler, text = 'She\'s pretty, but I am the kind of man who enjoys a long and healthy life.'})
keywordHandler:addKeyword({'special'}, StdModule.say, {npcHandler = npcHandler, text = 'My offers are permanently extraordinarily cheap.'})
keywordHandler:addKeyword({'artist'}, StdModule.say, {npcHandler = npcHandler, text = 'Yes! Selling is a form of art! The elaborate combination of rhetoric and acting which serves to create a sublime longing for the infinite, embodied by second class furniture.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Any time\'s a good time to buy some furniture.'})
keywordHandler:addKeyword({'quentin'}, StdModule.say, {npcHandler = npcHandler, text = 'That old monk has probably never left that overcrowded town here.'})
keywordHandler:addKeyword({'power'}, StdModule.say, {npcHandler = npcHandler, text = 'There are a few rumours about a rebellion, but that is all they are.'})
keywordHandler:addKeyword({'guild'}, StdModule.say, {npcHandler = npcHandler, text = 'Now those people really talk business. There is a new era dawning.'})
keywordHandler:addKeyword({'quest'}, StdModule.say, {npcHandler = npcHandler, text = 'A quest?! Who needs quests when there is interior decorating!'})
keywordHandler:addKeyword({'bozo'}, StdModule.say, {npcHandler = npcHandler, text = 'Bozo! Damn that clown! He keeps making fake orders. It isn\'t funny to deliver a wardrobe to an address that doesn\'t even exist, you know!'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am Thais\'s foremost furniture salesman.'})
keywordHandler:addKeyword({'creeps'}, StdModule.say, {npcHandler = npcHandler, text = 'Yes! I can never figure out which is which. And they are always watching me!'})
keywordHandler:addKeyword({'Topsy'}, StdModule.say, {npcHandler = npcHandler, text = 'Ah, those twins. Strange people they are (*sigh*). Oh, they are great to work with, of course. Excellent quality, competetive prices! But well... (whispers) they give me the creeps!'})
keywordHandler:addKeyword({'quality'}, StdModule.say, {npcHandler = npcHandler, text = 'Our furniture is produced by the finest carpenters on the continent using the rare wood of the Venorean marsh willow!'})
keywordHandler:addKeyword({'rebellion'}, StdModule.say, {npcHandler = npcHandler, text = 'Well - a few paranoid souls think that Venore wants to gain independence from Thais. Nothing more than rumours.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'barrel'}, 2793, 12, 'barrel')
shopModule:addBuyableItem({'still'}, 2640, 50, 'still')
shopModule:addBuyableItem({'yellow'}, 2650, 25, 'yellow')
shopModule:addBuyableItem({'god'}, 2981, 5, 'god')
shopModule:addBuyableItem({'goblin'}, 2804, 50, 'goblin')
shopModule:addBuyableItem({'green'}, 2776, 40, 'green')
shopModule:addBuyableItem({'trunk'}, 2794, 10, 'trunk')
shopModule:addBuyableItem({'dresser'}, 2790, 25, 'dresser')
shopModule:addBuyableItem({'potted'}, 2985, 5, 'potted')
shopModule:addBuyableItem({'knight'}, 2802, 50, 'knight')
shopModule:addBuyableItem({'oval'}, 2638, 40, 'oval')
shopModule:addBuyableItem({'crate'}, 2471, 10, 'crate')
shopModule:addBuyableItem({'pendulum'}, 2801, 75, 'pendulum')
shopModule:addBuyableItem({'flower'}, 2983, 6, 'flower')
shopModule:addBuyableItem({'orange'}, 2653, 25, 'orange')
shopModule:addBuyableItem({'green'}, 2647, 25, 'green')
shopModule:addBuyableItem({'vase'}, 2876, 3, 'vase')
shopModule:addBuyableItem({'orange'}, 2390, 20, 'orange')
shopModule:addBuyableItem({'turquoise'}, 2401, 25, 'turquoise')
shopModule:addBuyableItem({'landscape'}, 2639, 50, 'landscape')
shopModule:addBuyableItem({'purple'}, 2400, 25, 'purple')
shopModule:addBuyableItem({'rocking'}, 2778, 25, 'rocking')
shopModule:addBuyableItem({'round'}, 2783, 25, 'round')
shopModule:addBuyableItem({'harp'}, 2808, 50, 'harp')
shopModule:addBuyableItem({'piano'}, 2807, 200, 'piano')
shopModule:addBuyableItem({'yellow'}, 2397, 25, 'yellow')
shopModule:addBuyableItem({'table'}, 2798, 35, 'table')
shopModule:addBuyableItem({'blue'}, 2398, 25, 'blue')
shopModule:addBuyableItem({'birdcage'}, 2796, 50, 'birdcage')
shopModule:addBuyableItem({'green'}, 2387, 20, 'green')
shopModule:addBuyableItem({'red'}, 2775, 40, 'red')
shopModule:addBuyableItem({'big'}, 2785, 30, 'big')
shopModule:addBuyableItem({'turquoise'}, 2391, 20, 'turquoise')
shopModule:addBuyableItem({'white'}, 2392, 20, 'white')
shopModule:addBuyableItem({'red'}, 2388, 20, 'red')
shopModule:addBuyableItem({'christmas'}, 2812, 50, 'christmas')
shopModule:addBuyableItem({'small'}, 2782, 20, 'small')
shopModule:addBuyableItem({'indoor'}, 2811, 8, 'indoor')
shopModule:addBuyableItem({'edged'}, 2635, 40, 'edged')
shopModule:addBuyableItem({'blue'}, 2394, 25, 'blue')
shopModule:addBuyableItem({'telescope'}, 2799, 70, 'telescope')
shopModule:addBuyableItem({'red'}, 2399, 25, 'red')
shopModule:addBuyableItem({'honey'}, 2984, 5, 'honey')
shopModule:addBuyableItem({'globe'}, 2797, 50, 'globe')
shopModule:addBuyableItem({'heart'}, 2393, 30, 'heart')
shopModule:addBuyableItem({'rocking'}, 2800, 30, 'rocking')
shopModule:addBuyableItem({'purple'}, 2644, 25, 'purple')
shopModule:addBuyableItem({'round'}, 2632, 40, 'round')
shopModule:addBuyableItem({'purple'}, 2386, 20, 'purple')
shopModule:addBuyableItem({'blue'}, 2389, 20, 'blue')
shopModule:addBuyableItem({'locker'}, 2791, 30, 'locker')
shopModule:addBuyableItem({'trough'}, 2792, 7, 'trough')
shopModule:addBuyableItem({'white'}, 2667, 25, 'white')
shopModule:addBuyableItem({'wooden'}, 2777, 15, 'wooden')
shopModule:addBuyableItem({'amphora'}, 2893, 4, 'amphora')
shopModule:addBuyableItem({'red'}, 2656, 25, 'red')
shopModule:addBuyableItem({'sofa'}, 2779, 55, 'sofa')
shopModule:addBuyableItem({'cuckoo'}, 2664, 40, 'cuckoo')
shopModule:addBuyableItem({'blue'}, 2659, 25, 'blue')
shopModule:addBuyableItem({'coal'}, 2806, 25, 'coal')
shopModule:addBuyableItem({'portrait'}, 2641, 50, 'portrait')
shopModule:addBuyableItem({'large'}, 2805, 50, 'large')
shopModule:addBuyableItem({'red'}, 2395, 25, 'red')
shopModule:addBuyableItem({'green'}, 2396, 25, 'green')
shopModule:addBuyableItem({'water'}, 2974, 40, 'water')
shopModule:addBuyableItem({'minotaur'}, 2803, 50, 'minotaur')
shopModule:addBuyableItem({'drawer'}, 2789, 18, 'drawer')
shopModule:addBuyableItem({'chest'}, 2472, 10, 'chest')
shopModule:addBuyableItem({'square'}, 2784, 25, 'square')
shopModule:addBuyableItem({'box'}, 2469, 10, 'box')

npcHandler:addModule(FocusModule:new())

