local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Be mourned pilgrim in flesh.')
npcHandler:setMessage(MESSAGE_FAREWELL, 'May enlightenment be your path.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'May enlightenment be your path.')
keywordHandler:addKeyword({'shield'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling wooden shields and steel shields. What do you want?'})
keywordHandler:addKeyword({'ascension'}, StdModule.say, {npcHandler = npcHandler, text = 'This is nothing I understand. I am but a simple man.'})
keywordHandler:addKeyword({'weapon'}, StdModule.say, {npcHandler = npcHandler, text = 'I have hand axes, axes, spears, maces, battle hammers, swords, rapiers, daggers, and sabres. What\'s your choice?'})
keywordHandler:addKeyword({'trousers'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling chain legs. Do you want to buy any?'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'My offers are weapons, armors, helmets, legs, and shields.'})
keywordHandler:addKeyword({'oldpharaoh'}, StdModule.say, {npcHandler = npcHandler, text = 'Praised be our pharaoh who gave his father all the time in the world for contemplation and ascension.'})
keywordHandler:addKeyword({'armor'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling leather, chain, and brass armor. What do you need?'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell weapons and armor to protect your mortal shell.'})
keywordHandler:addKeyword({'daraman'}, StdModule.say, {npcHandler = npcHandler, text = 'Daraman is acknowledged as a prophet, though it is said he was misguided. I think you should better ask somebody in the temple about such issues.'})
keywordHandler:addKeyword({'ankrahmun'}, StdModule.say, {npcHandler = npcHandler, text = 'Our home is blessed and protected by the power of our pharaoh.'})
keywordHandler:addKeyword({'temple'}, StdModule.say, {npcHandler = npcHandler, text = 'You will find the temple in the northeastern part of the town.'})
keywordHandler:addKeyword({'palace'}, StdModule.say, {npcHandler = npcHandler, text = 'That\'s where our pharaohs resides. The palace is to the east.'})
keywordHandler:addKeyword({'kazordoon'}, StdModule.say, {npcHandler = npcHandler, text = 'I have been told the dwarves are worthy fighters. It is a shame their Rah will perish upon death.'})
keywordHandler:addKeyword({'darama'}, StdModule.say, {npcHandler = npcHandler, text = 'The continent\'s name was changed to Darama after Daraman spread his teachings here. I don\'t know its old name, I\'m afraid.'})
keywordHandler:addKeyword({'Rah'}, StdModule.say, {npcHandler = npcHandler, text = 'The Rah is what people from other religions call the soul.'})
keywordHandler:addKeyword({'pharaoh'}, StdModule.say, {npcHandler = npcHandler, text = 'The pharaoh is a living god and his power is rising with every day.'})
keywordHandler:addKeyword({'Akh'}, StdModule.say, {npcHandler = npcHandler, text = 'Well, that is the mortal body. It is full of needs and thus sinful.'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'This world is but a dying spark of a once great fire.'})
keywordHandler:addKeyword({'scarab'}, StdModule.say, {npcHandler = npcHandler, text = 'The scarabs are wise as far as I know. They test each warrior\'s strength.'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Time is only a burden to the flesh.'})
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'The lost cities of the Tibian continent are caught in their false gods\' jaws.'})
keywordHandler:addKeyword({'undead'}, StdModule.say, {npcHandler = npcHandler, text = 'Undeath must be great. No need to eat, to sleep or to do other things like that, you know.'})
keywordHandler:addKeyword({'uthun'}, StdModule.say, {npcHandler = npcHandler, text = 'That\'s what we learn and remember. It is who we are because of our memories. At least that\'s what I understand.'})
keywordHandler:addKeyword({'mourn'}, StdModule.say, {npcHandler = npcHandler, text = 'Mortality is a bad thing. The dead mourn us for that. Quite nice of them. We should mourn ourselves as well, if I understand the priests correctly.'})
keywordHandler:addKeyword({'arena'}, StdModule.say, {npcHandler = npcHandler, text = 'The arena is a fun place to visit. You should go there to try out our quality equipment.'})
keywordHandler:addKeyword({'helmet'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling leather helmets and chain helmets. What do you want?'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the mourned Memech.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'sword'}, 3264, 85, 'sword')
shopModule:addBuyableItem({'dagger'}, 3267, 5, 'dagger')
shopModule:addBuyableItem({'wooden'}, 3412, 15, 'wooden')
shopModule:addBuyableItem({'chain'}, 3358, 200, 'chain')
shopModule:addBuyableItem({'axe'}, 3274, 20, 'axe')
shopModule:addBuyableItem({'battle'}, 3305, 350, 'battle')
shopModule:addBuyableItem({'throwing'}, 3287, 50, 'throwing')
shopModule:addBuyableItem({'yes'}, 3366, 6400, 'yes')
shopModule:addBuyableItem({'hand'}, 3268, 8, 'hand')
shopModule:addBuyableItem({'leather'}, 3355, 12, 'leather')
shopModule:addBuyableItem({'spear'}, 3277, 10, 'spear')
shopModule:addBuyableItem({'mace'}, 3286, 90, 'mace')
shopModule:addBuyableItem({'steel'}, 3409, 240, 'steel')
shopModule:addBuyableItem({'chain'}, 3558, 80, 'chain')
shopModule:addBuyableItem({'chain'}, 3352, 52, 'chain')
shopModule:addBuyableItem({'rapier'}, 3272, 15, 'rapier')
shopModule:addBuyableItem({'leather'}, 3361, 35, 'leather')
shopModule:addBuyableItem({'sabre'}, 3273, 35, 'sabre')
shopModule:addBuyableItem({'brass'}, 3359, 450, 'brass')
shopModule:addSellableItem({'sell'}, 3282, 90, 'sell')
shopModule:addSellableItem({'sell'}, 3412, 5, 'sell')
shopModule:addSellableItem({'sell'}, 3267, 2, 'sell')
shopModule:addSellableItem({'sell'}, 3269, 400, 'sell')
shopModule:addSellableItem({'sell'}, 3274, 7, 'sell')
shopModule:addSellableItem({'sell'}, 3305, 120, 'sell')
shopModule:addSellableItem({'sell'}, 3268, 4, 'sell')
shopModule:addSellableItem({'sell'}, 3409, 80, 'sell')
shopModule:addSellableItem({'sell'}, 3294, 10, 'sell')
shopModule:addSellableItem({'sell'}, 3355, 4, 'sell')
shopModule:addSellableItem({'sell'}, 3277, 3, 'sell')
shopModule:addSellableItem({'sell'}, 3359, 150, 'sell')
shopModule:addSellableItem({'sell'}, 3286, 30, 'sell')
shopModule:addSellableItem({'sell'}, 3358, 70, 'sell')
shopModule:addSellableItem({'sell'}, 3357, 400, 'sell')
shopModule:addSellableItem({'sell'}, 3352, 17, 'sell')
shopModule:addSellableItem({'sell'}, 3272, 5, 'sell')
shopModule:addSellableItem({'sell'}, 3265, 450, 'sell')
shopModule:addSellableItem({'sell'}, 3270, 1, 'sell')
shopModule:addSellableItem({'sell'}, 3413, 95, 'sell')
shopModule:addSellableItem({'sell'}, 3361, 12, 'sell')
shopModule:addSellableItem({'sell'}, 3558, 25, 'sell')
shopModule:addSellableItem({'sell'}, 3351, 190, 'sell')
shopModule:addSellableItem({'sell'}, 3273, 12, 'sell')
shopModule:addSellableItem({'sell'}, 3264, 25, 'sell')
shopModule:addSellableItem({'sell'}, 3266, 80, 'sell')

npcHandler:addModule(FocusModule:new())

