local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Welcome |PLAYERNAME|! Whats your need?')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Good bye, |PLAYERNAME|')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Good bye, |PLAYERNAME|')
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Time is of no meaning to us sorcerers.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the head alchemist of Carlin. I keep the secret recipies of our ancestors. Besides, I am selling mana and life fluids, spellbooks, wands, rods and runes.'})
keywordHandler:addKeyword({'vocation'}, StdModule.say, {npcHandler = npcHandler, text = 'Your vocation is your profession. There are four vocations in Tibia: Sorcerers, paladins, knights, and druids.'})
keywordHandler:addKeyword({'ancestor'}, StdModule.say, {npcHandler = npcHandler, text = 'We are a guild of old traditions and even older secrets.'})
keywordHandler:addKeyword({'patience'}, StdModule.say, {npcHandler = npcHandler, text = 'You have to free yourself from unpatience to learn the deeper secrets of magic.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the illusterous Rachel, of course.'})
keywordHandler:addKeyword({'power'}, StdModule.say, {npcHandler = npcHandler, text = 'Power is important, but it is just the way, not the ultimate goal.'})
keywordHandler:addKeyword({'sorcerer'}, StdModule.say, {npcHandler = npcHandler, text = 'Spells are the minor parts that make a sorcerer. To be one is a state of mind, not of a full spellbook.'})
keywordHandler:addKeyword({'wisdom'}, StdModule.say, {npcHandler = npcHandler, text = 'Wisdom arises from patience.'})
keywordHandler:addKeyword({'goal'}, StdModule.say, {npcHandler = npcHandler, text = 'This secrect will be taught you by life, not by me.'})
keywordHandler:addKeyword({'deposit'}, StdModule.say, {npcHandler = npcHandler, text = 'I will pay you 5 gold for every empty vial. Ok?'})
keywordHandler:addKeyword({'rune'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell blank runes and spell runes.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'wand'}, 3075, 1000, 'wand')
shopModule:addBuyableItem({'ultimate'}, 3160, 175, 'ultimate')
shopModule:addBuyableItem({'fire'}, 3190, 245, 'fire')
shopModule:addBuyableItem({'snakebite'}, 3066, 500, 'snakebite')
shopModule:addBuyableItem({'fireball'}, 3189, 95, 'fireball')
shopModule:addBuyableItem({'energy'}, 3166, 340, 'energy')
shopModule:addBuyableItem({'destroy'}, 3148, 45, 'destroy')
shopModule:addBuyableItem({'heavy'}, 3198, 125, 'heavy')
shopModule:addBuyableItem({'convince'}, 3177, 80, 'convince')
shopModule:addBuyableItem({'volcanic'}, 3069, 5000, 'volcanic')
shopModule:addBuyableItem({'fire'}, 3188, 85, 'fire')
shopModule:addBuyableItem({'intense'}, 3152, 95, 'intense')
shopModule:addBuyableItem({'blank'}, 3147, 10, 'blank')
shopModule:addBuyableItem({'fire'}, 3192, 235, 'fire')
shopModule:addBuyableItem({'antidote'}, 3153, 65, 'antidote')
shopModule:addBuyableItem({'mana'}, 2874, 55, 'mana')
shopModule:addBuyableItem({'wand'}, 3072, 5000, 'wand')
shopModule:addBuyableItem({'wand'}, 3073, 10000, 'wand')
shopModule:addBuyableItem({'moonlight'}, 3070, 1000, 'moonlight')
shopModule:addBuyableItem({'quagmire'}, 3065, 10000, 'quagmire')
shopModule:addBuyableItem({'explosion'}, 3200, 250, 'explosion')
shopModule:addBuyableItem({'light'}, 3174, 40, 'light')
shopModule:addBuyableItem({'energy'}, 3164, 115, 'energy')
shopModule:addBuyableItem({'spellbook'}, 3059, 150, 'spellbook')
shopModule:addBuyableItem({'chameleon'}, 3178, 210, 'chameleon')
shopModule:addBuyableItem({'poison'}, 3172, 65, 'poison')
shopModule:addBuyableItem({'poison'}, 3176, 210, 'poison')
shopModule:addBuyableItem({'sudden'}, 3155, 325, 'sudden')
shopModule:addBuyableItem({'great'}, 3191, 180, 'great')
shopModule:addBuyableItem({'wand'}, 3074, 500, 'wand')
shopModule:addSellableItem({'sell'}, 3034, 320, 'sell')

npcHandler:addModule(FocusModule:new())

