local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Welcome to the finest weaponshop in the land, |PLAYERNAME|!')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Good bye. Come back soon.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Good bye. Come back soon.')
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Right now it\'s the current time.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am blacksmith and shopowner. If you need weapons or armor you are at the right place.'})
keywordHandler:addKeyword({'ghostlands'}, StdModule.say, {npcHandler = npcHandler, text = 'Only the mad would travel there ... the few sane people who went there returned mad. I am not comfortable with enemys from beyond the grave, you know?'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'My name is Rowenna.'})
keywordHandler:addKeyword({'thanks'}, StdModule.say, {npcHandler = npcHandler, text = 'You are welcome.'})
keywordHandler:addKeyword({'buy'}, StdModule.say, {npcHandler = npcHandler, text = 'What do you need? I sell only weapons. For armor, ask Cornelia.'})
keywordHandler:addKeyword({'sewer'}, StdModule.say, {npcHandler = npcHandler, text = 'Our city has a sewersystem, of course! But we leave it to the males to take care of it.'})
keywordHandler:addKeyword({'dungeon'}, StdModule.say, {npcHandler = npcHandler, text = 'In our fair city is no place for dungeons. I heared rumours that the crypts in the east are haunted.'})
keywordHandler:addKeyword({'monster'}, StdModule.say, {npcHandler = npcHandler, text = 'Are we talking about the fured or scaly ones or just about males? Ha, ha, ha!.'})
keywordHandler:addKeyword({'weapon'}, StdModule.say, {npcHandler = npcHandler, text = 'I have light and heavy weapons. What are you looking for?'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'My offers are light and heavy weapons.'})
keywordHandler:addKeyword({'light'}, StdModule.say, {npcHandler = npcHandler, text = 'I have clubs, daggers, spears, swords, maces, rapiers, morning stars, and sabres. What\'s your choice?'})
keywordHandler:addKeyword({'heavy'}, StdModule.say, {npcHandler = npcHandler, text = 'I have the best two handed swords in Tibia. I also sell battle hammers, battle axes, and the famous carlin swords. What\'s your choice?'})
keywordHandler:addKeyword({'help'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell and buy weapons. Some of the finest in the land, indeed.'})
keywordHandler:addKeyword({'armor'}, StdModule.say, {npcHandler = npcHandler, text = 'I sell only weapons. For armor, ask Cornelia in the other shop.'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'morning'}, 3282, 430, 'morning')
shopModule:addBuyableItem({'dagger'}, 3267, 5, 'dagger')
shopModule:addBuyableItem({'battle'}, 3305, 350, 'battle')
shopModule:addBuyableItem({'throwing'}, 3298, 25, 'throwing')
shopModule:addBuyableItem({'spear'}, 3277, 10, 'spear')
shopModule:addBuyableItem({'mace'}, 3286, 90, 'mace')
shopModule:addBuyableItem({'rapier'}, 3272, 15, 'rapier')
shopModule:addBuyableItem({'two'}, 3265, 950, 'two')
shopModule:addBuyableItem({'club'}, 3270, 5, 'club')
shopModule:addBuyableItem({'carlin'}, 3283, 473, 'carlin')
shopModule:addBuyableItem({'sabre'}, 3273, 25, 'sabre')
shopModule:addBuyableItem({'sword'}, 3264, 85, 'sword')
shopModule:addBuyableItem({'battle'}, 3266, 235, 'battle')
shopModule:addSellableItem({'sell'}, 3282, 100, 'sell')
shopModule:addSellableItem({'sell'}, 3267, 1, 'sell')
shopModule:addSellableItem({'sell'}, 3269, 310, 'sell')
shopModule:addSellableItem({'sell'}, 3305, 50, 'sell')
shopModule:addSellableItem({'sell'}, 3275, 260, 'sell')
shopModule:addSellableItem({'sell'}, 3277, 1, 'sell')
shopModule:addSellableItem({'sell'}, 3279, 470, 'sell')
shopModule:addSellableItem({'sell'}, 3286, 23, 'sell')
shopModule:addSellableItem({'sell'}, 3272, 3, 'sell')
shopModule:addSellableItem({'sell'}, 3265, 190, 'sell')
shopModule:addSellableItem({'sell'}, 3270, 1, 'sell')
shopModule:addSellableItem({'sell'}, 3283, 118, 'sell')
shopModule:addSellableItem({'sell'}, 3273, 5, 'sell')
shopModule:addSellableItem({'sell'}, 3294, 8, 'sell')
shopModule:addSellableItem({'sell'}, 3264, 15, 'sell')
shopModule:addSellableItem({'sell'}, 3266, 75, 'sell')

npcHandler:addModule(FocusModule:new())

