local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'HIHOOOO |PLAYERNAME|! <waves his hands>')
npcHandler:setMessage(MESSAGE_FAREWELL, 'YEAH, GO AWAY!')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'YEAH, GO AWAY!')
keywordHandler:addKeyword({'humans'}, StdModule.say, {npcHandler = npcHandler, text = 'A PROMISING RACE, SOME OF THEM ACTUALLY ADMIRE MECHANICS.'})
keywordHandler:addKeyword({'equipment'}, StdModule.say, {npcHandler = npcHandler, text = 'YOU ARE TOO STUPID FOR MOST OF OUR STUFF, BUT I COULD SELL YOU SOME CROSSBOWS.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'I BET I COULD BUILD A MACHINE TO SHRED HIM INTO PIECES!'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'ASK JIMBIN ABOUT HIS BREWS, NOT ME!'})
keywordHandler:addKeyword({'fight'}, StdModule.say, {npcHandler = npcHandler, text = 'NO, DONT SWITCH OUT THE LIGHT.'})
keywordHandler:addKeyword({'bezil'}, StdModule.say, {npcHandler = npcHandler, text = 'BEZIL AND NEZIL ARE RUNNING A SHOP.'})
keywordHandler:addKeyword({'jimbin'}, StdModule.say, {npcHandler = npcHandler, text = 'HIS BREWERY SAVED OUR DAY MORE THEN ONCE IN MANY WAYS.'})
keywordHandler:addKeyword({'earth'}, StdModule.say, {npcHandler = npcHandler, text = 'SORRY, BUT JUST DUST AND MUD TO ME.'})
keywordHandler:addKeyword({'uzgod'}, StdModule.say, {npcHandler = npcHandler, text = 'WE COULD MAKE FOR HIM MACHINES TO DO HIS WORK IN HALF THE TIME I BET.'})
keywordHandler:addKeyword({'pyromancer'}, StdModule.say, {npcHandler = npcHandler, text = 'OLD FOOLS, TO MUCH CONCERNED ABOUT TRADITION.'})
keywordHandler:addKeyword({'monster'}, StdModule.say, {npcHandler = npcHandler, text = 'I COULDN\'T CARE LESS ABOUT THEM.'})
keywordHandler:addKeyword({'kazordoon'}, StdModule.say, {npcHandler = npcHandler, text = 'WHAT?'})
keywordHandler:addKeyword({'etzel'}, StdModule.say, {npcHandler = npcHandler, text = 'WHO NEEDS MAGIC? PAH!'})
keywordHandler:addKeyword({'durin'}, StdModule.say, {npcHandler = npcHandler, text = 'I AM SURE HE WOULD BE SMART ENOUGH TO SEE THE CHANCES WE PROVIDE FOR DWARFENHOOD.'})
keywordHandler:addKeyword({'motos'}, StdModule.say, {npcHandler = npcHandler, text = 'STUPID IDIOT, WITH SOME MORE RESOURCES I COULD BUILD FOR HIM WARMACHINES BEYOND HIS WILDEST DREAMS! <insane laughter>'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'OLD FASHIONED BUTTERKNIFE! IF THEY LET ME, I WOULD CREATE WEAPONS THAT LEVEL ENTIRE CITIES!'})
keywordHandler:addKeyword({'kroox'}, StdModule.say, {npcHandler = npcHandler, text = 'WE COULD TEACH HIM MUCH IF HE LISTENED.'})
keywordHandler:addKeyword({'god'}, StdModule.say, {npcHandler = npcHandler, text = 'GODS, WHO NEEDS GODS, WHEN WE CAN BUILD THE CORRECT MACHINE FOR EVERY OCCASION?'})
keywordHandler:addKeyword({'fire'}, StdModule.say, {npcHandler = npcHandler, text = 'NICE RESOURCE FOR OUR MACHINES, BUT NO NEED TO MAKE A BIG DEAL ABOUT IT, JAWOLL!'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'CAN\'T TELL MUCH ABOUT IT. SELDOM GET OUT HERE, I AM A BUSY DWARF.'})
keywordHandler:addKeyword({'technomancer'}, StdModule.say, {npcHandler = npcHandler, text = 'WE ARE THE FUTURE. WE WILL BECOME A MAJOR POWER IN DWARFEN SOCIETY SOON! THEY WILL SEE, THEY WILL ALL SEE! <chuckles and rolls his eyes>'})
keywordHandler:addKeyword({'elves'}, StdModule.say, {npcHandler = npcHandler, text = 'NO. I DON\'T NEED ANY SHELVES!'})
keywordHandler:addKeyword({'heal'}, StdModule.say, {npcHandler = npcHandler, text = 'I AM AN ENGINEER, NOT A DOCTOR!'})
keywordHandler:addKeyword({'maryza'}, StdModule.say, {npcHandler = npcHandler, text = 'LOVELY, BUT PREDJUDICED AS MOST DWARFS ARE.'})
keywordHandler:addKeyword({'help'}, StdModule.say, {npcHandler = npcHandler, text = 'WHOM YOU ARE CALLING A WHELP, YOU &$(&*#!'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'ONE DAY OUR MACHINES WILL CHANGE THE ARMY STRUCTURES DRASTICALLY, JAWOLL!'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'ONE DAY I WILL CREATE A CLOCK FOR THE COLOSSUS'})
keywordHandler:addKeyword({'life'}, StdModule.say, {npcHandler = npcHandler, text = 'WHAT HIVE?'})
keywordHandler:addKeyword({'emperor'}, StdModule.say, {npcHandler = npcHandler, text = 'AT LEAST HES SMART ENOUGH TO LEAVE US ALONE, SO THERES HOPE FOR HIM.'})
keywordHandler:addKeyword({'offering'}, StdModule.say, {npcHandler = npcHandler, text = 'YES, THE MOST SOPHISTICATED ITEMS THEY BUY ARE CROSSBOWS.'})
keywordHandler:addKeyword({'citizen'}, StdModule.say, {npcHandler = npcHandler, text = 'YOU CAN BECOME CITIZEN IN THE HALL OF ANCIENTS.'})
keywordHandler:addKeyword({'colossus'}, StdModule.say, {npcHandler = npcHandler, text = 'NICE PIECE OF WORK. WOULD BE MORE FUN IF IT COULD MOVE AROUND... WE HAVE PLANS...'})
keywordHandler:addKeyword({'quest'}, StdModule.say, {npcHandler = npcHandler, text = 'BRING ME THE SCREWDRIVER OF KURIK AND I WILL REWARD YOU WITH A STEAMPOWERED SPIKESWORD!'})
keywordHandler:addKeyword({'plant'}, StdModule.say, {npcHandler = npcHandler, text = 'HEY! HOW DID YOU LEARN ABOUT OUR SECRET PLANT?'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'WHERE SHOULD I HOP?'})
keywordHandler:addKeyword({'uniform'}, StdModule.say, {npcHandler = npcHandler, text = 'NO, HERE IS NO UNICORN!'})
keywordHandler:addKeyword({'duria'}, StdModule.say, {npcHandler = npcHandler, text = 'KNIGHTS DO NOT HAVE THE BRAIN TO EVEN UNDERSTAND WHAT WE ARE OFFERING THEM.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I HAVE NO TIME FOR A GAME!'})
keywordHandler:addKeyword({'orcs'}, StdModule.say, {npcHandler = npcHandler, text = 'LET THEM COME, I AM WORKING ON A LITTLE SURPRISE FOR THEM! <chukles madly>'})
keywordHandler:addKeyword({'gold'}, StdModule.say, {npcHandler = npcHandler, text = 'DONATIONS ARE ALWAYS WELCOME!'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'crossbow'}, 3349, 1150, 'crossbow')
shopModule:addBuyableItem({'bolt'}, 3446, 5, 'bolt')

npcHandler:addModule(FocusModule:new())

