local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)			npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)		npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)	npcHandler:onCreatureSay(cid, type, msg)	end
function onThink()						npcHandler:onThink()						end
npcHandler:setMessage(MESSAGE_GREET, 'Greetings and Banor be with you, |PLAYERNAME|!')
npcHandler:setMessage(MESSAGE_FAREWELL, 'Farewell.')
npcHandler:setMessage(MESSAGE_WALKAWAY, 'Farewell.')
keywordHandler:addKeyword({'carlin'}, StdModule.say, {npcHandler = npcHandler, text = 'If the king sees the time is right, he will certainly start a campaign to reclaim what belongs to Thais.'})
keywordHandler:addKeyword({'job'}, StdModule.say, {npcHandler = npcHandler, text = 'I am the blacksmith of castle Bloodrock.'})
keywordHandler:addKeyword({'name'}, StdModule.say, {npcHandler = npcHandler, text = 'I am Willard, the smith.'})
keywordHandler:addKeyword({'trousers'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling chain legs. Do you want to buy any?'})
keywordHandler:addKeyword({'time'}, StdModule.say, {npcHandler = npcHandler, text = 'Now it is the current time.'})
keywordHandler:addKeyword({'helmet'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling leather helmets and chain helmets. What do you want?'})
keywordHandler:addKeyword({'army'}, StdModule.say, {npcHandler = npcHandler, text = 'I supply them with all they need.'})
keywordHandler:addKeyword({'king'}, StdModule.say, {npcHandler = npcHandler, text = 'Hail to the King! He\'s our benevolent protector.'})
keywordHandler:addKeyword({'buy'}, StdModule.say, {npcHandler = npcHandler, text = 'What do you need? I sell weapons, armors, helmets, and shields.'})
keywordHandler:addKeyword({'ferumbras'}, StdModule.say, {npcHandler = npcHandler, text = 'I would be honored if it\'s one of my blades that one day delivers him his punishment.'})
keywordHandler:addKeyword({'offer'}, StdModule.say, {npcHandler = npcHandler, text = 'My offers are weapons, ammunition, armors, helmets, legs, and shields.'})
keywordHandler:addKeyword({'ammunition'}, StdModule.say, {npcHandler = npcHandler, text = 'I have arrows for bows and bolts for crossbows. What do you want?'})
keywordHandler:addKeyword({'tibia'}, StdModule.say, {npcHandler = npcHandler, text = 'It\'s my dream that one day the whole world will profit from the Thaian governance.'})
keywordHandler:addKeyword({'news'}, StdModule.say, {npcHandler = npcHandler, text = 'Rumors are too sinister things that a true warrior would care for them.'})
keywordHandler:addKeyword({'thais'}, StdModule.say, {npcHandler = npcHandler, text = 'A fine city, but I love the peace of Edron more.'})
keywordHandler:addKeyword({'weapon'}, StdModule.say, {npcHandler = npcHandler, text = 'I have hand axes, axes, barbarian axes, spears, maces, clerical maces, battle hammers, swords, rapiers, daggers, sabres, bows, and crossbows. What\'s your choice?'})
keywordHandler:addKeyword({'shield'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling wooden shields, steel shields, and viking shields. What do you want?'})
keywordHandler:addKeyword({'edron'}, StdModule.say, {npcHandler = npcHandler, text = 'Edron is a fine city to live in.'})
keywordHandler:addKeyword({'excalibug'}, StdModule.say, {npcHandler = npcHandler, text = 'Adventurers search for this blade all over the world. Even here.'})
keywordHandler:addKeyword({'armor'}, StdModule.say, {npcHandler = npcHandler, text = 'I am selling leather, chain, and brass armor. What do you need?'})

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)
shopModule:addBuyableItem({'wooden'}, 3412, 15, 'wooden')
shopModule:addBuyableItem({'dagger'}, 3267, 5, 'dagger')
shopModule:addBuyableItem({'axe'}, 3274, 20, 'axe')
shopModule:addBuyableItem({'battle'}, 3305, 350, 'battle')
shopModule:addBuyableItem({'bolt'}, 3446, 3, 'bolt')
shopModule:addBuyableItem({'throwing'}, 3287, 50, 'throwing')
shopModule:addBuyableItem({'crossbow'}, 3349, 500, 'crossbow')
shopModule:addBuyableItem({'hand'}, 3268, 8, 'hand')
shopModule:addBuyableItem({'viking'}, 3431, 260, 'viking')
shopModule:addBuyableItem({'leather'}, 3361, 35, 'leather')
shopModule:addBuyableItem({'leather'}, 3355, 12, 'leather')
shopModule:addBuyableItem({'spear'}, 3277, 10, 'spear')
shopModule:addBuyableItem({'brass'}, 3359, 450, 'brass')
shopModule:addBuyableItem({'mace'}, 3286, 90, 'mace')
shopModule:addBuyableItem({'chain'}, 3358, 200, 'chain')
shopModule:addBuyableItem({'chain'}, 3558, 80, 'chain')
shopModule:addBuyableItem({'chain'}, 3352, 52, 'chain')
shopModule:addBuyableItem({'rapier'}, 3272, 15, 'rapier')
shopModule:addBuyableItem({'steel'}, 3409, 240, 'steel')
shopModule:addBuyableItem({'bow'}, 3350, 400, 'bow')
shopModule:addBuyableItem({'barbar'}, 3317, 590, 'barbar')
shopModule:addBuyableItem({'cleric'}, 3311, 540, 'cleric')
shopModule:addBuyableItem({'sabre'}, 3273, 35, 'sabre')
shopModule:addBuyableItem({'sword'}, 3264, 85, 'sword')
shopModule:addBuyableItem({'arrow'}, 3447, 2, 'arrow')
shopModule:addSellableItem({'sell'}, 3277, 3, 'sell')
shopModule:addSellableItem({'sell'}, 3409, 80, 'sell')
shopModule:addSellableItem({'sell'}, 3266, 80, 'sell')
shopModule:addSellableItem({'sell'}, 3311, 170, 'sell')
shopModule:addSellableItem({'sell'}, 3271, 240, 'sell')
shopModule:addSellableItem({'sell'}, 3317, 185, 'sell')
shopModule:addSellableItem({'sell'}, 3272, 5, 'sell')
shopModule:addSellableItem({'sell'}, 3558, 25, 'sell')
shopModule:addSellableItem({'sell'}, 3413, 95, 'sell')
shopModule:addSellableItem({'sell'}, 3353, 150, 'sell')
shopModule:addSellableItem({'sell'}, 3286, 30, 'sell')
shopModule:addSellableItem({'sell'}, 3269, 400, 'sell')
shopModule:addSellableItem({'sell'}, 3267, 2, 'sell')
shopModule:addSellableItem({'sell'}, 3431, 85, 'sell')
shopModule:addSellableItem({'sell'}, 3412, 5, 'sell')
shopModule:addSellableItem({'sell'}, 3361, 12, 'sell')
shopModule:addSellableItem({'sell'}, 3294, 10, 'sell')
shopModule:addSellableItem({'sell'}, 3351, 190, 'sell')
shopModule:addSellableItem({'sell'}, 3264, 25, 'sell')
shopModule:addSellableItem({'sell'}, 3355, 4, 'sell')
shopModule:addSellableItem({'sell'}, 3305, 120, 'sell')
shopModule:addSellableItem({'sell'}, 3274, 7, 'sell')
shopModule:addSellableItem({'sell'}, 3352, 17, 'sell')
shopModule:addSellableItem({'sell'}, 3265, 450, 'sell')
shopModule:addSellableItem({'sell'}, 3282, 90, 'sell')
shopModule:addSellableItem({'sell'}, 3358, 70, 'sell')
shopModule:addSellableItem({'sell'}, 3268, 4, 'sell')
shopModule:addSellableItem({'sell'}, 3359, 150, 'sell')
shopModule:addSellableItem({'sell'}, 3270, 1, 'sell')
shopModule:addSellableItem({'sell'}, 3273, 12, 'sell')
shopModule:addSellableItem({'sell'}, 3357, 400, 'sell')

npcHandler:addModule(FocusModule:new())

