<?php
/**
 * Tabela e Metadados Oficiais de Spells do Tibia 7.4 para MyAAC
 * Contém magias instantâneas, runas (com ML criação e uso) e conjurações.
 */

defined('MYAAC') or die('Direct access not allowed!');

return [
    // ==========================================
    // MAGIAS DE CURA (HEALING)
    // ==========================================
    [
        'id' => 1,
        'name' => 'Light Healing',
        'short_name' => '',
        'words' => 'exura',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 1,
        'maglevel_display' => 'ML 1',
        'maglevel_sort' => 1,
        'mana' => 25,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_1.png',
        'effect' => 'Restaura uma pequena quantidade de <b style="color:#2e7d32;">pontos de vida (HP)</b> do conjurador. A magia de cura mais básica e essencial para todas as vocações.'
    ],
    [
        'id' => 2,
        'name' => 'Intense Healing',
        'short_name' => '',
        'words' => 'exura gran',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 2,
        'maglevel_display' => 'ML 2',
        'maglevel_sort' => 2,
        'mana' => 40,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'icon' => 'images/spells/spell_2.png',
        'effect' => 'Restaura uma quantidade média de <b style="color:#2e7d32;">pontos de vida (HP)</b> do conjurador com ótima eficiência de mana.'
    ],
    [
        'id' => 3,
        'name' => 'Ultimate Healing',
        'short_name' => '',
        'words' => 'exura vita',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 8,
        'maglevel_display' => 'ML 8',
        'maglevel_sort' => 8,
        'mana' => 80,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'icon' => 'images/spells/spell_3.png',
        'effect' => 'Restaura a maior parte ou a totalidade dos <b style="color:#2e7d32;">pontos de vida (HP)</b> instantaneamente. Vital para magos e paladinos em caçadas e PvP.'
    ],
    [
        'id' => 4,
        'name' => 'Heal Friend',
        'short_name' => 'Sio',
        'words' => 'exura sio "nome',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 7,
        'maglevel_display' => 'ML 7',
        'maglevel_sort' => 7,
        'mana' => 70,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Druid'],
        'icon' => 'images/spells/spell_84.png',
        'effect' => 'Cura intensamente os <b style="color:#2e7d32;">pontos de vida</b> de um aliado a distância pelo nome entre aspas. Magia primordial dos Druidas em caçadas em grupo e guerras.'
    ],
    [
        'id' => 5,
        'name' => 'Mass Healing',
        'short_name' => 'Mas Res',
        'words' => 'exura gran mas res',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 19,
        'maglevel_display' => 'ML 19',
        'maglevel_sort' => 19,
        'mana' => 150,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Druid'],
        'icon' => 'images/spells/spell_82.png',
        'effect' => 'Cura em área todos os jogadores aliados e criaturas invocadas num raio ao redor do Druida.'
    ],
    [
        'id' => 6,
        'name' => 'Antidote',
        'short_name' => '',
        'words' => 'exana pox',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Cura',
        'maglevel' => 2,
        'maglevel_display' => 'ML 2',
        'maglevel_sort' => 2,
        'mana' => 30,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_29.png',
        'effect' => 'Neutraliza e cura instantaneamente a condição de <b style="color:#2e7d32;">envenenamento (poison)</b> do conjurador.'
    ],

    // ==========================================
    // MAGIAS DE ATAQUE (ATTACK)
    // ==========================================
    [
        'id' => 7,
        'name' => 'Berserk',
        'short_name' => 'Exori',
        'words' => 'exori',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 5,
        'maglevel_display' => 'ML 5',
        'maglevel_sort' => 5,
        'mana' => 0,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Knight'],
        'icon' => 'images/spells/spell_80.png',
        'effect' => 'Golpe giratório de fúria com a arma equipada. Causa alto <b style="color:#b71c1c;">dano físico</b> em todos os monstros e jogadores adjacentes (1 sqm ao redor). Consome toda a mana atual.'
    ],
    [
        'id' => 8,
        'name' => 'Fire Wave',
        'short_name' => '',
        'words' => 'exevo flam hur',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 7,
        'maglevel_display' => 'ML 7',
        'maglevel_sort' => 7,
        'mana' => 80,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_19.png',
        'effect' => 'Dispara uma potente onda de chamas em cone de até 4 sqm à frente com devastador <b style="color:#d32f2f;">dano de fogo</b>.'
    ],
    [
        'id' => 9,
        'name' => 'Energy Beam',
        'short_name' => '',
        'words' => 'exevo vis lux',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 10,
        'maglevel_display' => 'ML 10',
        'maglevel_sort' => 10,
        'mana' => 100,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_22.png',
        'effect' => 'Dispara um raio concentrado de pura energia em linha reta até 5 sqm à frente com <b style="color:#512da8;">dano de energia</b>.'
    ],
    [
        'id' => 10,
        'name' => 'Great Energy Beam',
        'short_name' => '',
        'words' => 'exevo gran vis lux',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 14,
        'maglevel_display' => 'ML 14',
        'maglevel_sort' => 14,
        'mana' => 200,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_23.png',
        'effect' => 'Dispara um feixe maciço de energia em linha reta de até 8 sqm à frente infligindo altíssimo <b style="color:#512da8;">dano de energia</b>.'
    ],
    [
        'id' => 11,
        'name' => 'Energy Wave',
        'short_name' => '',
        'words' => 'exevo mort hur',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 20,
        'maglevel_display' => 'ML 20',
        'maglevel_sort' => 20,
        'mana' => 250,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_13.png',
        'effect' => 'Dispara uma onda triangular de energia com grande abertura atingindo todos os alvos à frente com extremo <b style="color:#512da8;">dano de energia</b>.'
    ],
    [
        'id' => 12,
        'name' => 'Poison Storm',
        'short_name' => 'Mas Pox',
        'words' => 'exevo gran mas pox',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 28,
        'maglevel_display' => 'ML 28',
        'maglevel_sort' => 28,
        'mana' => 600,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Druid'],
        'icon' => 'images/spells/spell_56.png',
        'effect' => 'Invoca uma tempestade massiva de toxinas venenosas em toda a tela ao redor do Druida, aplicando <b style="color:#2e7d32;">dano contínuo letal de veneno</b>.'
    ],
    [
        'id' => 13,
        'name' => 'Ultimate Explosion',
        'short_name' => 'UE',
        'words' => 'exevo gran mas vis',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Ataque',
        'maglevel' => 40,
        'maglevel_display' => 'ML 40',
        'maglevel_sort' => 40,
        'mana' => 800,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_24.png',
        'effect' => 'A magia mais famosa e temida do Tibia 7.4. Detona uma explosão cósmica em toda a tela com <b style="color:#b71c1c;">dano físico devastador</b> que oblitera tudo no campo de visão.'
    ],

    // ==========================================
    // MAGIAS DE SUPORTE (SUPPORT)
    // ==========================================
    [
        'id' => 14,
        'name' => 'Challenge',
        'short_name' => 'Exeta Res',
        'words' => 'exeta res',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 4,
        'maglevel_display' => 'ML 4',
        'maglevel_sort' => 4,
        'mana' => 30,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Elite Knight'],
        'icon' => 'images/spells/spell_93.png',
        'effect' => 'Grito de provocação que força os monstros adjacentes a atacarem o cavaleiro em vez dos magos ou atiradores.'
    ],
    [
        'id' => 15,
        'name' => 'Haste',
        'short_name' => 'Hur',
        'words' => 'utani hur',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 4,
        'maglevel_display' => 'ML 4',
        'maglevel_sort' => 4,
        'mana' => 60,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_6.png',
        'effect' => 'Acelera a locomoção do personagem em <b style="color:#1565c0;">+30% de velocidade</b> durante 33 segundos.'
    ],
    [
        'id' => 16,
        'name' => 'Strong Haste',
        'short_name' => 'Gran Hur',
        'words' => 'utani gran hur',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 8,
        'maglevel_display' => 'ML 8',
        'maglevel_sort' => 8,
        'mana' => 100,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_39.png',
        'effect' => 'Super aceleração mágica. Aumenta a velocidade do mago em <b style="color:#1565c0;">+70%</b> durante 20 segundos.'
    ],
    [
        'id' => 17,
        'name' => 'Magic Shield',
        'short_name' => 'Utamo',
        'words' => 'utamo vita',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 4,
        'maglevel_display' => 'ML 4',
        'maglevel_sort' => 4,
        'mana' => 50,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'icon' => 'images/spells/spell_44.png',
        'effect' => 'Ativa o <b style="color:#1565c0;">Mana Shield</b> por 200 segundos. Todo o dano sofrido é absorvido pelos pontos de mana antes de tocar a vida.'
    ],
    [
        'id' => 18,
        'name' => 'Invisibility',
        'short_name' => 'Utana Vid',
        'words' => 'utana vid',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 15,
        'maglevel_display' => 'ML 15',
        'maglevel_sort' => 15,
        'mana' => 210,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'icon' => 'images/spells/spell_45.png',
        'effect' => 'Torna o conjurador completamente invisível durante 200 segundos contra monstros que não enxergam criaturas ocultas.'
    ],
    [
        'id' => 19,
        'name' => 'Summon Creature',
        'short_name' => 'Utevo Res',
        'words' => 'utevo res "monstro',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 16,
        'maglevel_display' => 'ML 16',
        'maglevel_sort' => 16,
        'mana' => 'Var.',
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_9.png',
        'effect' => 'Invoca até 2 monstros fiéis (como Orc Berserker, Monk, Demon Skeleton, Fire Devil) para lutar ao seu lado. O custo de mana depende da criatura.'
    ],
    [
        'id' => 20,
        'name' => 'Creature Illusion',
        'short_name' => '',
        'words' => 'utevo res ina "monstro',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 10,
        'maglevel_display' => 'ML 10',
        'maglevel_sort' => 10,
        'mana' => 100,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_38.png',
        'effect' => 'Muda temporariamente a aparência física do mago para a de um monstro especificado por 180 segundos.'
    ],
    [
        'id' => 21,
        'name' => 'Wild Growth',
        'short_name' => '',
        'words' => 'exevo grav vita',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 13,
        'maglevel_display' => 'ML 13',
        'maglevel_sort' => 13,
        'mana' => 220,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Elder Druid'],
        'icon' => 'images/spells/spell_94.png',
        'effect' => 'Brota arbustos densos intransponíveis no solo por 45 segundos, bloqueando corredores e caminhos em traps.'
    ],
    [
        'id' => 22,
        'name' => 'Undead Legion',
        'short_name' => '',
        'words' => 'exana mas mort',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 15,
        'maglevel_display' => 'ML 15',
        'maglevel_sort' => 15,
        'mana' => 500,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Druid'],
        'icon' => 'images/spells/spell_83.png',
        'effect' => 'Ressuscita todos os cadáveres recentes de criaturas no campo de visão como esqueletos obedientes sob o comando do Druida.'
    ],
    [
        'id' => 23,
        'name' => 'Levitate',
        'short_name' => '',
        'words' => 'exani hur "up / down',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 3,
        'maglevel_display' => 'ML 3',
        'maglevel_sort' => 3,
        'mana' => 50,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_81.png',
        'effect' => 'Permite levitar e subir (\'up\') ou descer (\'down\') de montanhas, plataformas e locais elevados.'
    ],
    [
        'id' => 24,
        'name' => 'Magic Rope',
        'short_name' => '',
        'words' => 'exani tera',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 1,
        'maglevel_display' => 'ML 1',
        'maglevel_sort' => 1,
        'mana' => 20,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_76.png',
        'effect' => 'Iça o conjurador para o andar superior através de orifícios de corda (Rope spots) sem a necessidade de uma corda física.'
    ],
    [
        'id' => 25,
        'name' => 'Find Person',
        'short_name' => 'Exiva',
        'words' => 'exiva "nome',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 0,
        'maglevel_display' => 'ML 0',
        'maglevel_sort' => 0,
        'mana' => 20,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_20.png',
        'effect' => 'Rastreia a posição de outro jogador informando a distância aproximada e direção cardeal (Norte, Sul, Leste, Oeste, andares).'
    ],
    [
        'id' => 26,
        'name' => 'Light',
        'short_name' => '',
        'words' => 'utevo lux',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 0,
        'maglevel_display' => 'ML 0',
        'maglevel_sort' => 0,
        'mana' => 20,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_10.png',
        'effect' => 'Ilumina um pequeno círculo ao redor do personagem durante 6 minutos.'
    ],
    [
        'id' => 27,
        'name' => 'Great Light',
        'short_name' => '',
        'words' => 'utevo gran lux',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 3,
        'maglevel_display' => 'ML 3',
        'maglevel_sort' => 3,
        'mana' => 60,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin', 'Knight'],
        'icon' => 'images/spells/spell_11.png',
        'effect' => 'Ilumina uma área ampla com claridade cristalina durante 11 minutos.'
    ],
    [
        'id' => 28,
        'name' => 'Ultimate Light',
        'short_name' => '',
        'words' => 'utevo vis lux',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 12,
        'maglevel_display' => 'ML 12',
        'maglevel_sort' => 12,
        'mana' => 140,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_75.png',
        'effect' => 'Ilumina intensamente toda a tela como se fosse a luz do meio-dia durante 33 minutos.'
    ],
    [
        'id' => 29,
        'name' => 'Cancel Invisibility',
        'short_name' => '',
        'words' => 'exana ina',
        'type' => 'instant',
        'type_label' => 'Instantânea',
        'group' => 'Suporte',
        'maglevel' => 12,
        'maglevel_display' => 'ML 12',
        'maglevel_sort' => 12,
        'mana' => 200,
        'charges' => '—',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'icon' => 'images/spells/spell_90.png',
        'effect' => 'Revela e desfaz a invisibilidade de todos os jogadores e criaturas ocultas no campo visual.'
    ],

    // ==========================================
    // RUNAS (RUNES) - COM ML DE CRIAÇÃO E USO
    // ==========================================
    [
        'id' => 30,
        'name' => 'Sudden Death',
        'short_name' => 'SD',
        'words' => 'adori vita vis',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2268,
        'maglevel' => 25,
        'maglevel_use' => 15,
        'maglevel_display' => 'Criação: <b>ML 25</b><br/><small style="color:#555;">Uso: <b>ML 15</b></small>',
        'maglevel_sort' => 25,
        'mana' => 220,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'use_vocations' => ['Todas as Vocações (ML 15+)'],
        'icon' => 'images/spells/spell_21.png',
        'effect' => 'A runa de ataque mais famosa e potente do jogo. Dispara uma esfera de energia negra causando <b style="color:#b71c1c;">altíssimo dano físico puro</b> no alvo selecionado.'
    ],
    [
        'id' => 31,
        'name' => 'Ultimate Healing Rune',
        'short_name' => 'UH',
        'words' => 'adura vita',
        'type' => 'rune',
        'type_label' => 'Runa de Cura',
        'group' => 'Runa de Cura',
        'item_id' => 2273,
        'maglevel' => 11,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 11</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 11,
        'mana' => 100,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Todas as Vocações (ML 4+)'],
        'icon' => 'images/spells/spell_5.png',
        'effect' => 'A runa primordial de cura do 7.4. Restaura massivamente os <b style="color:#2e7d32;">pontos de vida (HP)</b> de qualquer jogador ou criatura aliada.'
    ],
    [
        'id' => 32,
        'name' => 'Heavy Magic Missile',
        'short_name' => 'HMM',
        'words' => 'adori gran',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2311,
        'maglevel' => 3,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 3</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 3,
        'mana' => 70,
        'charges' => '5x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'icon' => 'images/spells/spell_8.png',
        'effect' => 'Dispara um míssil teleguiado de energia concentrada causando moderado <b style="color:#512da8;">dano de energia</b> com 5 cargas por runa.'
    ],
    [
        'id' => 33,
        'name' => 'Great Fireball',
        'short_name' => 'GFB',
        'words' => 'adori gran flam',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2304,
        'maglevel' => 9,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 9</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 9,
        'mana' => 120,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 4+)'],
        'icon' => 'images/spells/spell_16.png',
        'effect' => 'Detona uma enorme bola flamejante em grande área (5x5 sqm) causando intenso <b style="color:#d32f2f;">dano de fogo</b> em múltiplos alvos.'
    ],
    [
        'id' => 34,
        'name' => 'Explosion',
        'short_name' => '',
        'words' => 'adevo mas hur',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2313,
        'maglevel' => 12,
        'maglevel_use' => 6,
        'maglevel_display' => 'Criação: <b>ML 12</b><br/><small style="color:#555;">Uso: <b>ML 6</b></small>',
        'maglevel_sort' => 12,
        'mana' => 180,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 6+)'],
        'icon' => 'images/spells/spell_18.png',
        'effect' => 'Detona uma violenta explosão em área de 3x3 sqm causando <b style="color:#b71c1c;">dano físico puro</b> baseado no ML e Level do usuário.'
    ],
    [
        'id' => 35,
        'name' => 'Fireball',
        'short_name' => '',
        'words' => 'adori flam',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2302,
        'maglevel' => 5,
        'maglevel_use' => 2,
        'maglevel_display' => 'Criação: <b>ML 5</b><br/><small style="color:#555;">Uso: <b>ML 2</b></small>',
        'maglevel_sort' => 5,
        'mana' => 60,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 2+)'],
        'icon' => 'images/spells/spell_15.png',
        'effect' => 'Lança uma esfera flamejante em área de 3x3 sqm causando <b style="color:#d32f2f;">dano de fogo</b> moderado.'
    ],
    [
        'id' => 36,
        'name' => 'Light Magic Missile',
        'short_name' => 'LMM',
        'words' => 'adori',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2287,
        'maglevel' => 1,
        'maglevel_use' => 0,
        'maglevel_display' => 'Criação: <b>ML 1</b><br/><small style="color:#555;">Uso: <b>ML 0</b></small>',
        'maglevel_sort' => 1,
        'mana' => 40,
        'charges' => '10x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações'],
        'icon' => 'images/spells/spell_7.png',
        'effect' => 'Dispara um pequeno projétil teleguiado de energia mágica. Muito econômica com 10 cargas por runa.'
    ],
    [
        'id' => 37,
        'name' => 'Magic Wall',
        'short_name' => 'M-Wall',
        'words' => 'adevo grav tera',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2293,
        'maglevel' => 14,
        'maglevel_use' => 9,
        'maglevel_display' => 'Criação: <b>ML 14</b><br/><small style="color:#555;">Uso: <b>ML 9</b></small>',
        'maglevel_sort' => 14,
        'mana' => 250,
        'charges' => '4x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'use_vocations' => ['Todas as Vocações (ML 9+)'],
        'icon' => 'images/spells/spell_86.png',
        'effect' => 'Ergue uma parede sólida e impenetrável de energia cristalina durante 20 segundos. Indispensável para guerras e traps.'
    ],
    [
        'id' => 38,
        'name' => 'Paralyze',
        'short_name' => '',
        'words' => 'adana ani',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2278,
        'maglevel' => 35,
        'maglevel_use' => 18,
        'maglevel_display' => 'Criação: <b>ML 35</b><br/><small style="color:#555;">Uso: <b>ML 18</b></small>',
        'maglevel_sort' => 35,
        'mana' => 900,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Druid'],
        'icon' => 'images/spells/spell_54.png',
        'effect' => 'Paralisa drasticamente a velocidade do jogador alvo, deixando-o quase estático até que ele conjures uma magia de cura (exura/gran/vita/sio).'
    ],
    [
        'id' => 39,
        'name' => 'Fire Field',
        'short_name' => '',
        'words' => 'adevo grav flam',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2301,
        'maglevel' => 3,
        'maglevel_use' => 1,
        'maglevel_display' => 'Criação: <b>ML 3</b><br/><small style="color:#555;">Uso: <b>ML 1</b></small>',
        'maglevel_sort' => 3,
        'mana' => 60,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 1+)'],
        'icon' => 'images/spells/spell_25.png',
        'effect' => 'Cria 1 campo de chamas persistente no chão que incendeia qualquer monstro ou jogador que passar por cima.'
    ],
    [
        'id' => 40,
        'name' => 'Fire Wall',
        'short_name' => '',
        'words' => 'adevo mas grav flam',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2303,
        'maglevel' => 13,
        'maglevel_use' => 6,
        'maglevel_display' => 'Criação: <b>ML 13</b><br/><small style="color:#555;">Uso: <b>ML 6</b></small>',
        'maglevel_sort' => 13,
        'mana' => 200,
        'charges' => '4x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 6+)'],
        'icon' => 'images/spells/spell_28.png',
        'effect' => 'Cria uma muralha reta de 5 campos de fogo bloqueando a passagem de monstros vulneráveis a chamas.'
    ],
    [
        'id' => 41,
        'name' => 'Firebomb',
        'short_name' => '',
        'words' => 'adevo mas flam',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2305,
        'maglevel' => 9,
        'maglevel_use' => 5,
        'maglevel_display' => 'Criação: <b>ML 9</b><br/><small style="color:#555;">Uso: <b>ML 5</b></small>',
        'maglevel_sort' => 9,
        'mana' => 150,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 5+)'],
        'icon' => 'images/spells/spell_17.png',
        'effect' => 'Cria uma área em cruz de 3x3 sqm de labaredas intensas no solo impedindo e queimando monstros.'
    ],
    [
        'id' => 42,
        'name' => 'Energy Field',
        'short_name' => '',
        'words' => 'adevo grav vis',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2277,
        'maglevel' => 5,
        'maglevel_use' => 3,
        'maglevel_display' => 'Criação: <b>ML 5</b><br/><small style="color:#555;">Uso: <b>ML 3</b></small>',
        'maglevel_sort' => 5,
        'mana' => 80,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 3+)'],
        'icon' => 'images/spells/spell_27.png',
        'effect' => 'Cria 1 campo de energia no chão eletrocutando com <b style="color:#512da8;">dano contínuo de energia</b> quem passar.'
    ],
    [
        'id' => 43,
        'name' => 'Energy Wall',
        'short_name' => '',
        'words' => 'adevo mas grav vis',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2279,
        'maglevel' => 18,
        'maglevel_use' => 9,
        'maglevel_display' => 'Criação: <b>ML 18</b><br/><small style="color:#555;">Uso: <b>ML 9</b></small>',
        'maglevel_sort' => 18,
        'mana' => 250,
        'charges' => '4x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 9+)'],
        'icon' => 'images/spells/spell_33.png',
        'effect' => 'Ergue uma barreira de 5 campos de energia intransponíveis para a grande maioria das criaturas do jogo.'
    ],
    [
        'id' => 44,
        'name' => 'Energybomb',
        'short_name' => '',
        'words' => 'adevo mas vis',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2262,
        'maglevel' => 18,
        'maglevel_use' => 10,
        'maglevel_display' => 'Criação: <b>ML 18</b><br/><small style="color:#555;">Uso: <b>ML 10</b></small>',
        'maglevel_sort' => 18,
        'mana' => 220,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer'],
        'use_vocations' => ['Todas as Vocações (ML 10+)'],
        'icon' => 'images/spells/spell_55.png',
        'effect' => 'Inunda uma área de 3x3 sqm no solo com 9 campos de alta voltagem elétrica.'
    ],
    [
        'id' => 45,
        'name' => 'Poison Field',
        'short_name' => '',
        'words' => 'adevo grav pox',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2285,
        'maglevel' => 2,
        'maglevel_use' => 0,
        'maglevel_display' => 'Criação: <b>ML 2</b><br/><small style="color:#555;">Uso: <b>ML 0</b></small>',
        'maglevel_sort' => 2,
        'mana' => 50,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações'],
        'icon' => 'images/spells/spell_26.png',
        'effect' => 'Cria 1 poça de veneno que intoxica inimigos e bloqueia a passagem de monstros vulneráveis.'
    ],
    [
        'id' => 46,
        'name' => 'Poison Wall',
        'short_name' => '',
        'words' => 'adevo mas grav pox',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2289,
        'maglevel' => 11,
        'maglevel_use' => 5,
        'maglevel_display' => 'Criação: <b>ML 11</b><br/><small style="color:#555;">Uso: <b>ML 5</b></small>',
        'maglevel_sort' => 11,
        'mana' => 160,
        'charges' => '4x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 5+)'],
        'icon' => 'images/spells/spell_32.png',
        'effect' => 'Cria uma linha reta de 5 campos de veneno denso e tóxico.'
    ],
    [
        'id' => 47,
        'name' => 'Poisonbomb',
        'short_name' => '',
        'words' => 'adevo mas pox',
        'type' => 'rune',
        'type_label' => 'Runa de Campo',
        'group' => 'Runa de Campo',
        'item_id' => 2286,
        'maglevel' => 8,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 8</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 8,
        'mana' => 130,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Todas as Vocações (ML 4+)'],
        'icon' => 'images/spells/spell_91.png',
        'effect' => 'Detona uma explosão de toxinas cobrindo uma área de 3x3 sqm com veneno.'
    ],
    [
        'id' => 48,
        'name' => 'Soulfire',
        'short_name' => '',
        'words' => 'adevo res flam',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2308,
        'maglevel' => 13,
        'maglevel_use' => 7,
        'maglevel_display' => 'Criação: <b>ML 13</b><br/><small style="color:#555;">Uso: <b>ML 7</b></small>',
        'maglevel_sort' => 13,
        'mana' => 150,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Todas as Vocações (ML 7+)'],
        'icon' => 'images/spells/spell_50.png',
        'effect' => 'Marca a alma do alvo incendiando-o com <b style="color:#d32f2f;">queimadura contínua</b> que persiste por vários minutos sem se apagar.'
    ],
    [
        'id' => 49,
        'name' => 'Envenom',
        'short_name' => '',
        'words' => 'adevo res pox',
        'type' => 'rune',
        'type_label' => 'Runa de Ataque',
        'group' => 'Runa de Ataque',
        'item_id' => 2292,
        'maglevel' => 7,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 7</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 7,
        'mana' => 100,
        'charges' => '2x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Druid'],
        'icon' => 'images/spells/spell_58.png',
        'effect' => 'Dispara uma dose de veneno concentrado que intoxica o alvo a distância.'
    ],
    [
        'id' => 50,
        'name' => 'Intense Healing Rune',
        'short_name' => 'IH',
        'words' => 'adura gran',
        'type' => 'rune',
        'type_label' => 'Runa de Cura',
        'group' => 'Runa de Cura',
        'item_id' => 2265,
        'maglevel' => 4,
        'maglevel_use' => 1,
        'maglevel_display' => 'Criação: <b>ML 4</b><br/><small style="color:#555;">Uso: <b>ML 1</b></small>',
        'maglevel_sort' => 4,
        'mana' => 60,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Todas as Vocações (ML 1+)'],
        'icon' => 'images/spells/spell_4.png',
        'effect' => 'Cura uma quantidade moderada de vida de si mesmo ou de outro jogador aliado.'
    ],
    [
        'id' => 51,
        'name' => 'Antidote Rune',
        'short_name' => '',
        'words' => 'adana pox',
        'type' => 'rune',
        'type_label' => 'Runa de Cura',
        'group' => 'Runa de Cura',
        'item_id' => 2266,
        'maglevel' => 5,
        'maglevel_use' => 0,
        'maglevel_display' => 'Criação: <b>ML 5</b><br/><small style="color:#555;">Uso: <b>ML 0</b></small>',
        'maglevel_sort' => 5,
        'mana' => 50,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Todas as Vocações'],
        'icon' => 'images/spells/spell_31.png',
        'effect' => 'Remove o veneno de si ou de um companheiro a distância usando uma runa.'
    ],
    [
        'id' => 52,
        'name' => 'Destroy Field',
        'short_name' => '',
        'words' => 'adito grav',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2261,
        'maglevel' => 6,
        'maglevel_use' => 3,
        'maglevel_display' => 'Criação: <b>ML 6</b><br/><small style="color:#555;">Uso: <b>ML 3</b></small>',
        'maglevel_sort' => 6,
        'mana' => 60,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'use_vocations' => ['Todas as Vocações (ML 3+)'],
        'icon' => 'images/spells/spell_30.png',
        'effect' => 'Dissipa e apaga campos de fogo, energia ou veneno do chão num sqm especificado.'
    ],
    [
        'id' => 53,
        'name' => 'Desintegrate',
        'short_name' => '',
        'words' => 'adito tera',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2310,
        'maglevel' => 8,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 8</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 8,
        'mana' => 100,
        'charges' => '3x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid', 'Paladin'],
        'use_vocations' => ['Todas as Vocações (ML 4+)'],
        'icon' => 'images/spells/spell_78.png',
        'effect' => 'Desintegra e pulveriza corpos, caixas e entulhos de 1 sqm adjacente para desobstruir caminhos.'
    ],
    [
        'id' => 54,
        'name' => 'Convince Creature',
        'short_name' => '',
        'words' => 'adeta sio',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2290,
        'maglevel' => 10,
        'maglevel_use' => 5,
        'maglevel_display' => 'Criação: <b>ML 10</b><br/><small style="color:#555;">Uso: <b>ML 5</b></small>',
        'maglevel_sort' => 10,
        'mana' => 100,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_12.png',
        'effect' => 'Domina a mente de uma criatura selvagem transformando-a em seu animal de estimação obediente.'
    ],
    [
        'id' => 55,
        'name' => 'Chameleon',
        'short_name' => '',
        'words' => 'adevo ina',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2291,
        'maglevel' => 11,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 11</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 11,
        'mana' => 150,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Druid'],
        'use_vocations' => ['Todas as Vocações (ML 4+)'],
        'icon' => 'images/spells/spell_14.png',
        'effect' => 'Camufla o usuário fazendo-o assumir a aparência física exata de qualquer item que estiver no chão.'
    ],
    [
        'id' => 56,
        'name' => 'Animate Dead',
        'short_name' => '',
        'words' => 'adana mort',
        'type' => 'rune',
        'type_label' => 'Runa de Suporte',
        'group' => 'Runa de Suporte',
        'item_id' => 2316,
        'maglevel' => 7,
        'maglevel_use' => 4,
        'maglevel_display' => 'Criação: <b>ML 7</b><br/><small style="color:#555;">Uso: <b>ML 4</b></small>',
        'maglevel_sort' => 7,
        'mana' => 300,
        'charges' => '1x',
        'reagent' => 'Blank Rune',
        'premium' => 0,
        'vocations' => ['Sorcerer', 'Druid'],
        'use_vocations' => ['Sorcerer', 'Druid'],
        'icon' => 'images/spells/spell_83.png',
        'effect' => 'Ressuscita o cadáver de uma criatura transformando-o num esqueleto leal para lutar ao seu lado.'
    ],

    // ==========================================
    // CONJURAÇÕES DE MUNIÇÃO E ARMAS (CONJURE)
    // ==========================================
    [
        'id' => 57,
        'name' => 'Create Food',
        'short_name' => '',
        'words' => 'exevo pan',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 0,
        'maglevel_display' => 'ML 0',
        'maglevel_sort' => 0,
        'mana' => 30,
        'charges' => 'Var.',
        'premium' => 0,
        'vocations' => ['Druid', 'Paladin'],
        'icon' => 'images/spells/spell_42.png',
        'effect' => 'Conjura alimentos mágicos variados (carnes, presuntos, maçãs) diretamente na mochila para saciar a fome.'
    ],
    [
        'id' => 58,
        'name' => 'Conjure Arrow',
        'short_name' => '',
        'words' => 'exevo con',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 2,
        'maglevel_display' => 'ML 2',
        'maglevel_sort' => 2,
        'mana' => 40,
        'charges' => '30x',
        'premium' => 0,
        'vocations' => ['Paladin'],
        'icon' => 'images/spells/spell_51.png',
        'effect' => 'Conjura 30 flechas normais para uso com arcos.'
    ],
    [
        'id' => 59,
        'name' => 'Conjure Bolt',
        'short_name' => '',
        'words' => 'exevo con mort',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 6,
        'maglevel_display' => 'ML 6',
        'maglevel_sort' => 6,
        'mana' => 70,
        'charges' => '20x',
        'premium' => 0,
        'vocations' => ['Paladin'],
        'icon' => 'images/spells/spell_79.png',
        'effect' => 'Conjura 20 virotes de besta (bolts) com bom poder de perfuração.'
    ],
    [
        'id' => 60,
        'name' => 'Explosive Arrow',
        'short_name' => '',
        'words' => 'exevo con flam',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 10,
        'maglevel_display' => 'ML 10',
        'maglevel_sort' => 10,
        'mana' => 120,
        'charges' => '10x',
        'premium' => 0,
        'vocations' => ['Paladin'],
        'icon' => 'images/spells/spell_49.png',
        'effect' => 'Conjura 10 flechas explosivas que detonam dano físico e de fogo em área (3x3 sqm) ao atingir o alvo.'
    ],
    [
        'id' => 61,
        'name' => 'Poisoned Arrow',
        'short_name' => '',
        'words' => 'exevo con pox',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 5,
        'maglevel_display' => 'ML 5',
        'maglevel_sort' => 5,
        'mana' => 70,
        'charges' => '20x',
        'premium' => 0,
        'vocations' => ['Paladin'],
        'icon' => 'images/spells/spell_48.png',
        'effect' => 'Conjura 20 flechas com ponta embebida em veneno letal que intoxica o alvo atingido.'
    ],
    [
        'id' => 62,
        'name' => 'Power Bolt',
        'short_name' => '',
        'words' => 'exevo con vis',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 14,
        'maglevel_display' => 'ML 14',
        'maglevel_sort' => 14,
        'mana' => 200,
        'charges' => '2x',
        'premium' => 0,
        'vocations' => ['Paladin'],
        'icon' => 'images/spells/spell_95.png',
        'effect' => 'Conjura 2 virotes de precisão pesados (Power Bolts) com altíssimo poder de ataque (40 Atk).'
    ],
    [
        'id' => 63,
        'name' => 'Enchant Staff',
        'short_name' => '',
        'words' => 'exeta vis',
        'type' => 'conjure',
        'type_label' => 'Conjuração',
        'group' => 'Conjuração',
        'maglevel' => 22,
        'maglevel_display' => 'ML 22',
        'maglevel_sort' => 22,
        'mana' => 80,
        'charges' => '—',
        'premium' => 1,
        'vocations' => ['Master Sorcerer'],
        'icon' => 'images/spells/spell_92.png',
        'effect' => 'Requer um cajado simples (Wooden Staff). Encanta o cajado transformando-o temporariamente em uma Enchanted Staff mística de alto poder.'
    ]
];
