<?php
/**
 * Tabela Oficial de Magias, Runas e Conjurações do Tibia 7.4 para MyAAC
 * Sincronizado 100% com server/data/spells/spells.xml
 */

defined('MYAAC') or die('Direct access not allowed!');

return [
  [
    'id' => 1,
    'name' => "Light Healing",
    'popular_alias' => "",
    'words' => "exura",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 1,
    'maglevel_display' => '<strong>ML 1</strong>',
    'maglevel_sort' => 1,
    'mana' => 25,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/light_healing.gif",
    'status_icon' => "",
    'effect_pt' => "Restaura uma pequena quantidade de <span class=\"effect-heal\">vida (HP)</span> do conjurador.",
    'effect_en' => "Restores a small amount of <span class=\"effect-heal\">hit points (HP)</span> of the caster.",
    'effect' => "Restaura uma pequena quantidade de <span class=\"effect-heal\">vida (HP)</span> do conjurador.",
  ],
  [
    'id' => 2,
    'name' => "Intense Healing",
    'popular_alias' => "",
    'words' => "exura gran",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 2,
    'maglevel_display' => '<strong>ML 2</strong>',
    'maglevel_sort' => 2,
    'mana' => 40,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/intense_healing.gif",
    'status_icon' => "",
    'effect_pt' => "Restaura uma quantidade média de <span class=\"effect-heal\">vida (HP)</span> com boa eficiência.",
    'effect_en' => "Restores a moderate amount of <span class=\"effect-heal\">hit points (HP)</span> efficiently.",
    'effect' => "Restaura uma quantidade média de <span class=\"effect-heal\">vida (HP)</span> com boa eficiência.",
  ],
  [
    'id' => 3,
    'name' => "Ultimate Healing",
    'popular_alias' => "",
    'words' => "exura vita",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 8,
    'maglevel_display' => '<strong>ML 8</strong>',
    'maglevel_sort' => 8,
    'mana' => 80,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/ultimate_healing.gif",
    'status_icon' => "",
    'effect_pt' => "Restaura grande quantidade ou o total de <span class=\"effect-heal\">vida (HP)</span> instantaneamente.",
    'effect_en' => "Restores a large or full amount of <span class=\"effect-heal\">hit points (HP)</span> instantly.",
    'effect' => "Restaura grande quantidade ou o total de <span class=\"effect-heal\">vida (HP)</span> instantaneamente.",
  ],
  [
    'id' => 4,
    'name' => "Heal Friend",
    'popular_alias' => "Sio",
    'words' => "exura sio \"nome",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 7,
    'maglevel_display' => '<strong>ML 7</strong>',
    'maglevel_sort' => 7,
    'mana' => 70,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Druid"],
    'icon' => "images/spells/wiki/heal_friend.gif",
    'status_icon' => "",
    'effect_pt' => "Cura um companheiro ou aliado à distância pelo nome.",
    'effect_en' => "Heals a targeted party member or friend by character name.",
    'effect' => "Cura um companheiro ou aliado à distância pelo nome.",
  ],
  [
    'id' => 5,
    'name' => "Mass Healing",
    'popular_alias' => "Mas Res",
    'words' => "exura gran mas res",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 19,
    'maglevel_display' => '<strong>ML 19</strong>',
    'maglevel_sort' => 19,
    'mana' => 150,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Druid"],
    'icon' => "images/spells/wiki/mass_healing.gif",
    'status_icon' => "",
    'effect_pt' => "Cura em área todos os jogadores aliados e invocações ao redor do Druida.",
    'effect_en' => "Restores the hit points of all friendly players and summons around the Druid.",
    'effect' => "Cura em área todos os jogadores aliados e invocações ao redor do Druida.",
  ],
  [
    'id' => 6,
    'name' => "Antidote",
    'popular_alias' => "",
    'words' => "exana pox",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Cura",
    'group_en' => "Healing",
    'maglevel' => 2,
    'maglevel_display' => '<strong>ML 2</strong>',
    'maglevel_sort' => 2,
    'mana' => 30,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/antidote.gif",
    'status_icon' => "",
    'effect_pt' => "Neutraliza e cura instantaneamente a condição de <span class=\"effect-poison\">envenenamento</span>.",
    'effect_en' => "Immediately neutralizes and cures the condition of <span class=\"effect-poison\">poisoning</span>.",
    'effect' => "Neutraliza e cura instantaneamente a condição de <span class=\"effect-poison\">envenenamento</span>.",
  ],
  [
    'id' => 7,
    'name' => "Berserk",
    'popular_alias' => "Exori",
    'words' => "exori",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 5,
    'maglevel_display' => '<strong>ML 5</strong>',
    'maglevel_sort' => 5,
    'mana' => 0,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Knight"],
    'icon' => "images/spells/wiki/berserk.gif",
    'status_icon' => "bleeding.gif",
    'effect_pt' => "<img src=\"images/spells/status/bleeding.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Golpe giratório com a arma causando alto <span class=\"effect-phys\">dano físico</span> em área (1 sqm ao redor).",
    'effect_en' => "<img src=\"images/spells/status/bleeding.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Fierce spinning weapon strike dealing high <span class=\"effect-phys\">physical damage</span> in a 1-sqm radius.",
    'effect' => "<img src=\"images/spells/status/bleeding.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Golpe giratório com a arma causando alto <span class=\"effect-phys\">dano físico</span> em área (1 sqm ao redor).",
  ],
  [
    'id' => 8,
    'name' => "Fire Wave",
    'popular_alias' => "F-Wave",
    'words' => "exevo flam hur",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 7,
    'maglevel_display' => '<strong>ML 7</strong>',
    'maglevel_sort' => 7,
    'mana' => 80,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/fire_wave.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara uma onda de chamas em cone até 4 sqm à frente com <span class=\"effect-fire\">dano de fogo</span>.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Shoots a cone wave of flames up to 4 sqm ahead with <span class=\"effect-fire\">fire damage</span>.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara uma onda de chamas em cone até 4 sqm à frente com <span class=\"effect-fire\">dano de fogo</span>.",
  ],
  [
    'id' => 9,
    'name' => "Energy Beam",
    'popular_alias' => "",
    'words' => "exevo vis lux",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 10,
    'maglevel_display' => '<strong>ML 10</strong>',
    'maglevel_sort' => 10,
    'mana' => 100,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/energy_beam.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara um raio concentrado em linha reta até 5 sqm com <span class=\"effect-energy\">dano de energia</span>.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Shoots a concentrated straight electrical beam up to 5 sqm with <span class=\"effect-energy\">energy damage</span>.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara um raio concentrado em linha reta até 5 sqm com <span class=\"effect-energy\">dano de energia</span>.",
  ],
  [
    'id' => 10,
    'name' => "Great Energy Beam",
    'popular_alias' => "",
    'words' => "exevo gran vis lux",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 14,
    'maglevel_display' => '<strong>ML 14</strong>',
    'maglevel_sort' => 14,
    'mana' => 200,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/great_energy_beam.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara um feixe maciço de energia em linha reta até 8 sqm com alto <span class=\"effect-energy\">dano</span>.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Shoots a massive straight energy beam up to 8 sqm with high <span class=\"effect-energy\">damage</span>.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara um feixe maciço de energia em linha reta até 8 sqm com alto <span class=\"effect-energy\">dano</span>.",
  ],
  [
    'id' => 11,
    'name' => "Energy Wave",
    'popular_alias' => "E-Wave",
    'words' => "exevo mort hur",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 20,
    'maglevel_display' => '<strong>ML 20</strong>',
    'maglevel_sort' => 20,
    'mana' => 250,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/energy_wave.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Onda triangular de energia com grande abertura frontal e extremo <span class=\"effect-energy\">dano</span>.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Wide triangular cone wave dealing extreme <span class=\"effect-energy\">energy damage</span>.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Onda triangular de energia com grande abertura frontal e extremo <span class=\"effect-energy\">dano</span>.",
  ],
  [
    'id' => 12,
    'name' => "Poison Storm",
    'popular_alias' => "Mas Pox",
    'words' => "exevo gran mas pox",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 28,
    'maglevel_display' => '<strong>ML 28</strong>',
    'maglevel_sort' => 28,
    'mana' => 600,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Druid"],
    'icon' => "images/spells/wiki/poison_storm.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Tempestade de <span class=\"effect-poison\">veneno</span> em toda a tela causando envenenamento severo.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Screen-wide <span class=\"effect-poison\">poison</span> storm causing severe persistent poison condition.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Tempestade de <span class=\"effect-poison\">veneno</span> em toda a tela causando envenenamento severo.",
  ],
  [
    'id' => 13,
    'name' => "Ultimate Explosion",
    'popular_alias' => "UE",
    'words' => "exevo gran mas vis",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Ataque",
    'group_en' => "Attack",
    'maglevel' => 40,
    'maglevel_display' => '<strong>ML 40</strong>',
    'maglevel_sort' => 40,
    'mana' => 800,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/ultimate_explosion.gif",
    'status_icon' => "physical.gif",
    'effect_pt' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Explosão catastrófica de dano devastador atingindo quase todos os alvos da tela.",
    'effect_en' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Catastrophic explosion of devastating damage hitting almost all targets on screen.",
    'effect' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Explosão catastrófica de dano devastador atingindo quase todos os alvos da tela.",
  ],
  [
    'id' => 14,
    'name' => "Challenge",
    'popular_alias' => "",
    'words' => "exeta res",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 4,
    'maglevel_display' => '<strong>ML 4</strong>',
    'maglevel_sort' => 4,
    'mana' => 30,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Elite Knight"],
    'icon' => "images/spells/wiki/challenge.gif",
    'status_icon' => "",
    'effect_pt' => "Provoca todos os monstros adjacentes a focarem os ataques no Knight.",
    'effect_en' => "Provokes adjacent monsters to focus their attacks on the Knight.",
    'effect' => "Provoca todos os monstros adjacentes a focarem os ataques no Knight.",
  ],
  [
    'id' => 15,
    'name' => "Haste",
    'popular_alias' => "",
    'words' => "utani hur",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 4,
    'maglevel_display' => '<strong>ML 4</strong>',
    'maglevel_sort' => 4,
    'mana' => 60,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/haste.gif",
    'status_icon' => "haste.gif",
    'effect_pt' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Aumenta a <span class=\"effect-speed\">velocidade de movimento</span> do conjurador por 33 segundos.",
    'effect_en' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Increases the caster <span class=\"effect-speed\">movement speed</span> for 33 seconds.",
    'effect' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Aumenta a <span class=\"effect-speed\">velocidade de movimento</span> do conjurador por 33 segundos.",
  ],
  [
    'id' => 16,
    'name' => "Strong Haste",
    'popular_alias' => "Gran Hur",
    'words' => "utani gran hur",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 8,
    'maglevel_display' => '<strong>ML 8</strong>',
    'maglevel_sort' => 8,
    'mana' => 100,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid"],
    'icon' => "images/spells/wiki/strong_haste.gif",
    'status_icon' => "haste.gif",
    'effect_pt' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Aumento extremo na <span class=\"effect-speed\">velocidade de movimento</span> dos magos por 20 segundos.",
    'effect_en' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Extreme boost in <span class=\"effect-speed\">movement speed</span> for mages for 20 seconds.",
    'effect' => "<img src=\"images/spells/status/haste.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Aumento extremo na <span class=\"effect-speed\">velocidade de movimento</span> dos magos por 20 segundos.",
  ],
  [
    'id' => 17,
    'name' => "Magic Shield",
    'popular_alias' => "",
    'words' => "utamo vita",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 4,
    'maglevel_display' => '<strong>ML 4</strong>',
    'maglevel_sort' => 4,
    'mana' => 50,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Elite Knight"],
    'icon' => "images/spells/wiki/magic_shield.gif",
    'status_icon' => "magic_shield.gif",
    'effect_pt' => "<img src=\"images/spells/status/magic_shield.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Escudo místico onde todo o dano recebido é absorvido pela Mana em vez da Vida.",
    'effect_en' => "<img src=\"images/spells/status/magic_shield.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Mystic shield redirecting all incoming damage to Mana instead of Hit Points.",
    'effect' => "<img src=\"images/spells/status/magic_shield.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Escudo místico onde todo o dano recebido é absorvido pela Mana em vez da Vida.",
  ],
  [
    'id' => 18,
    'name' => "Invisibility",
    'popular_alias' => "",
    'words' => "utana vid",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 15,
    'maglevel_display' => '<strong>ML 15</strong>',
    'maglevel_sort' => 15,
    'mana' => 210,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/invisibility.gif",
    'status_icon' => "",
    'effect_pt' => "Torna o jogador completamente invisível a monstros comuns por 200 segundos.",
    'effect_en' => "Renders the player completely invisible to regular monsters for 200 seconds.",
    'effect' => "Torna o jogador completamente invisível a monstros comuns por 200 segundos.",
  ],
  [
    'id' => 19,
    'name' => "Cancel Invisibility",
    'popular_alias' => "",
    'words' => "exana ina",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 12,
    'maglevel_display' => '<strong>ML 12</strong>',
    'maglevel_sort' => 12,
    'mana' => 200,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer"],
    'icon' => "images/spells/wiki/cancel_invisibility.gif",
    'status_icon' => "",
    'effect_pt' => "Cancela e revela a invisibilidade de criaturas e jogadores na tela.",
    'effect_en' => "Dispels and reveals invisibility of creatures and players in view.",
    'effect' => "Cancela e revela a invisibilidade de criaturas e jogadores na tela.",
  ],
  [
    'id' => 20,
    'name' => "Summon Creature",
    'popular_alias' => "",
    'words' => "utevo res \"monstro",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 16,
    'maglevel_display' => '<strong>ML 16</strong>',
    'maglevel_sort' => 16,
    'mana' => 0,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'icon' => "images/spells/wiki/summon_creature.gif",
    'status_icon' => "",
    'effect_pt' => "Invoca monstros leais (ex: Demon Skeleton, Monge, Orc Leader). O custo de mana depende da criatura.",
    'effect_en' => "Summons loyal allied creatures (e.g. Demon Skeleton, Monk). Mana cost varies.",
    'effect' => "Invoca monstros leais (ex: Demon Skeleton, Monge, Orc Leader). O custo de mana depende da criatura.",
  ],
  [
    'id' => 21,
    'name' => "Creature Illusion",
    'popular_alias' => "",
    'words' => "utevo res ina \"monstro",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 10,
    'maglevel_display' => '<strong>ML 10</strong>',
    'maglevel_sort' => 10,
    'mana' => 100,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'icon' => "images/spells/wiki/creature_illusion.gif",
    'status_icon' => "",
    'effect_pt' => "Disfarça a aparência do conjurador na forma visual de um monstro escolhido por 3 minutos.",
    'effect_en' => "Disguises the visual appearance of the caster into a chosen monster for 3 minutes.",
    'effect' => "Disfarça a aparência do conjurador na forma visual de um monstro escolhido por 3 minutos.",
  ],
  [
    'id' => 22,
    'name' => "Wild Growth",
    'popular_alias' => "",
    'words' => "exevo grav vita",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 13,
    'maglevel_display' => '<strong>ML 13</strong>',
    'maglevel_sort' => 13,
    'mana' => 220,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Elder Druid"],
    'icon' => "images/spells/wiki/wild_growth.gif",
    'status_icon' => "",
    'effect_pt' => "Cria uma densa muralha de plantas intransponível que bloqueia passagem e projéteis.",
    'effect_en' => "Sprouts impassable thick vegetation blocking all movement and projectile paths.",
    'effect' => "Cria uma densa muralha de plantas intransponível que bloqueia passagem e projéteis.",
  ],
  [
    'id' => 23,
    'name' => "Undead Legion",
    'popular_alias' => "",
    'words' => "exana mas mort",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 15,
    'maglevel_display' => '<strong>ML 15</strong>',
    'maglevel_sort' => 15,
    'mana' => 500,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Druid"],
    'icon' => "images/spells/wiki/undead_legion.gif",
    'status_icon' => "",
    'effect_pt' => "Reanima todos os cadáveres ao redor transformando-os em Esqueletos aliados.",
    'effect_en' => "Raises all nearby fresh corpses into obedient allied skeletons.",
    'effect' => "Reanima todos os cadáveres ao redor transformando-os em Esqueletos aliados.",
  ],
  [
    'id' => 24,
    'name' => "Levitate",
    'popular_alias' => "",
    'words' => "exani hur \"up / down",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 3,
    'maglevel_display' => '<strong>ML 3</strong>',
    'maglevel_sort' => 3,
    'mana' => 50,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/levitate.gif",
    'status_icon' => "",
    'effect_pt' => "Permite subir ou descer despenhadeiros, montanhas e telhados sem escadas.",
    'effect_en' => "Allows ascending or descending cliffs and roofs without ladders.",
    'effect' => "Permite subir ou descer despenhadeiros, montanhas e telhados sem escadas.",
  ],
  [
    'id' => 25,
    'name' => "Magic Rope",
    'popular_alias' => "",
    'words' => "exani tera",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 1,
    'maglevel_display' => '<strong>ML 1</strong>',
    'maglevel_sort' => 1,
    'mana' => 20,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/magic_rope.gif",
    'status_icon' => "",
    'effect_pt' => "Funciona como uma corda mágica para subir buracos em rope spots sem precisar do item físico.",
    'effect_en' => "Acts as a magic rope to climb rope spots without needing a physical rope item.",
    'effect' => "Funciona como uma corda mágica para subir buracos em rope spots sem precisar do item físico.",
  ],
  [
    'id' => 26,
    'name' => "Find Person",
    'popular_alias' => "",
    'words' => "exiva \"nome",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 0,
    'maglevel_display' => '<strong>ML 0</strong>',
    'maglevel_sort' => 0,
    'mana' => 20,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/find_person.gif",
    'status_icon' => "",
    'effect_pt' => "Revela a direção e distância aproximada de outro jogador no mapa do mundo.",
    'effect_en' => "Reveals the direction and approximate distance to another player on the map.",
    'effect' => "Revela a direção e distância aproximada de outro jogador no mapa do mundo.",
  ],
  [
    'id' => 27,
    'name' => "Light",
    'popular_alias' => "",
    'words' => "utevo lux",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 0,
    'maglevel_display' => '<strong>ML 0</strong>',
    'maglevel_sort' => 0,
    'mana' => 20,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/light.gif",
    'status_icon' => "",
    'effect_pt' => "Ilumina uma pequena área ao redor do personagem por 6 minutos.",
    'effect_en' => "Illuminates a small area around the character for 6 minutes.",
    'effect' => "Ilumina uma pequena área ao redor do personagem por 6 minutos.",
  ],
  [
    'id' => 28,
    'name' => "Great Light",
    'popular_alias' => "",
    'words' => "utevo gran lux",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 3,
    'maglevel_display' => '<strong>ML 3</strong>',
    'maglevel_sort' => 3,
    'mana' => 60,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/great_light.gif",
    'status_icon' => "",
    'effect_pt' => "Ilumina intensamente uma ampla área ao redor por mais de 11 minutos.",
    'effect_en' => "Intensely illuminates a wide radius for more than 11 minutes.",
    'effect' => "Ilumina intensamente uma ampla área ao redor por mais de 11 minutos.",
  ],
  [
    'id' => 29,
    'name' => "Ultimate Light",
    'popular_alias' => "",
    'words' => "utevo vis lux",
    'type' => "instant",
    'type_label' => 'Instantânea',
    'group' => "Suporte",
    'group_en' => "Support",
    'maglevel' => 12,
    'maglevel_display' => '<strong>ML 12</strong>',
    'maglevel_sort' => 12,
    'mana' => 140,
    'charges' => "—",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid"],
    'icon' => "images/spells/wiki/ultimate_light.gif",
    'status_icon' => "",
    'effect_pt' => "Iluminação máxima permanente cobrindo a tela inteira por 33 minutos.",
    'effect_en' => "Maximum illumination covering the entire screen for 33 minutes.",
    'effect' => "Iluminação máxima permanente cobrindo a tela inteira por 33 minutos.",
  ],
  [
    'id' => 30,
    'name' => "Sudden Death",
    'popular_alias' => "SD",
    'words' => "adori vita vis",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 25,
    'use_maglevel' => 15,
    'maglevel_display' => 'Uso: <strong>ML 15</strong><div class="spell-ml-sub">Fazer: ML 25</div>',
    'maglevel_sort' => 15,
    'mana' => 220,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/sudden_death.gif",
    'status_icon' => "physical.gif",
    'effect_pt' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara o mais letal ataque concentrado de <span class=\"effect-phys\">dano de morte</span> do jogo.",
    'effect_en' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Fires the single most lethal concentrated <span class=\"effect-phys\">death damage</span> blast in the game.",
    'effect' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara o mais letal ataque concentrado de <span class=\"effect-phys\">dano de morte</span> do jogo.",
  ],
  [
    'id' => 31,
    'name' => "Ultimate Healing Rune",
    'popular_alias' => "UH",
    'words' => "adura vita",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Cura",
    'group_en' => "Healing Rune",
    'maglevel' => 11,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 11</div>',
    'maglevel_sort' => 4,
    'mana' => 100,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/ultimate_healing_rune.gif",
    'status_icon' => "",
    'effect_pt' => "Restaura quase toda a <span class=\"effect-heal\">vida</span> do alvo ou conjurador. Runa sagrada dos Druidas no 7.4.",
    'effect_en' => "Restores almost all <span class=\"effect-heal\">hit points</span> of target or caster. Sacred Druid rune.",
    'effect' => "Restaura quase toda a <span class=\"effect-heal\">vida</span> do alvo ou conjurador. Runa sagrada dos Druidas no 7.4.",
  ],
  [
    'id' => 32,
    'name' => "Heavy Magic Missile",
    'popular_alias' => "HMM",
    'words' => "adori gran",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 3,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 3</div>',
    'maglevel_sort' => 4,
    'mana' => 70,
    'charges' => "5x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/heavy_magic_missile.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Míssil pesado de <span class=\"effect-energy\">energia</span> com 5 cargas de alta eficiência de caça.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Heavy <span class=\"effect-energy\">energy</span> missile with 5 charges and great hunting efficiency.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Míssil pesado de <span class=\"effect-energy\">energia</span> com 5 cargas de alta eficiência de caça.",
  ],
  [
    'id' => 33,
    'name' => "Great Fireball",
    'popular_alias' => "GFB",
    'words' => "adori gran flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 9,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 9</div>',
    'maglevel_sort' => 4,
    'mana' => 120,
    'charges' => "2x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/great_fireball.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Imensa bola de <span class=\"effect-fire\">fogo</span> atingindo vasta área circular de até 37 sqm.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Immense ball of <span class=\"effect-fire\">fire</span> striking a vast circular blast radius of up to 37 sqm.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Imensa bola de <span class=\"effect-fire\">fogo</span> atingindo vasta área circular de até 37 sqm.",
  ],
  [
    'id' => 34,
    'name' => "Explosion",
    'popular_alias' => "Explo",
    'words' => "adevo mas hur",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 12,
    'use_maglevel' => 6,
    'maglevel_display' => 'Uso: <strong>ML 6</strong><div class="spell-ml-sub">Fazer: ML 12</div>',
    'maglevel_sort' => 6,
    'mana' => 180,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/explosion.gif",
    'status_icon' => "physical.gif",
    'effect_pt' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Detonação de <span class=\"effect-phys\">dano físico</span> em área 3x3 (9 sqm). Muito usada por Knights e Paladins.",
    'effect_en' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Detonation of <span class=\"effect-phys\">physical damage</span> over a 3x3 area (9 sqm). Popular with Knights and Paladins.",
    'effect' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Detonação de <span class=\"effect-phys\">dano físico</span> em área 3x3 (9 sqm). Muito usada por Knights e Paladins.",
  ],
  [
    'id' => 35,
    'name' => "Fireball",
    'popular_alias' => "",
    'words' => "adori flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 5,
    'use_maglevel' => 2,
    'maglevel_display' => 'Uso: <strong>ML 2</strong><div class="spell-ml-sub">Fazer: ML 5</div>',
    'maglevel_sort' => 2,
    'mana' => 60,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/fireball.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara uma bola de <span class=\"effect-fire\">fogo</span> com dano moderado em área 3x3.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Launches a <span class=\"effect-fire\">fireball</span> with moderate damage covering a 3x3 area.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Dispara uma bola de <span class=\"effect-fire\">fogo</span> com dano moderado em área 3x3.",
  ],
  [
    'id' => 36,
    'name' => "Light Magic Missile",
    'popular_alias' => "LMM",
    'words' => "adori",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 1,
    'use_maglevel' => 0,
    'maglevel_display' => 'Uso: <strong>ML 0</strong><div class="spell-ml-sub">Fazer: ML 1</div>',
    'maglevel_sort' => 0,
    'mana' => 40,
    'charges' => "5x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/light_magic_missile.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Míssil leve de <span class=\"effect-energy\">energia</span> com 10 cargas para iniciantes sem exigência de ML para uso.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Light <span class=\"effect-energy\">energy</span> missile with 10 charges and no ML requirement to use.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Míssil leve de <span class=\"effect-energy\">energia</span> com 10 cargas para iniciantes sem exigência de ML para uso.",
  ],
  [
    'id' => 37,
    'name' => "Magic Wall",
    'popular_alias' => "M-Wall",
    'words' => "adevo grav tera",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 14,
    'use_maglevel' => 9,
    'maglevel_display' => 'Uso: <strong>ML 9</strong><div class="spell-ml-sub">Fazer: ML 14</div>',
    'maglevel_sort' => 9,
    'mana' => 250,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/magic_wall.gif",
    'status_icon' => "",
    'effect_pt' => "Cria uma parede mística intransponível por 20 segundos para controle de combate.",
    'effect_en' => "Conjures an impassable energy barrier lasting 20 seconds for tactical control.",
    'effect' => "Cria uma parede mística intransponível por 20 segundos para controle de combate.",
  ],
  [
    'id' => 38,
    'name' => "Paralyze",
    'popular_alias' => "Paralyze",
    'words' => "adana ani",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 35,
    'use_maglevel' => 18,
    'maglevel_display' => 'Uso: <strong>ML 18</strong><div class="spell-ml-sub">Fazer: ML 35</div>',
    'maglevel_sort' => 18,
    'mana' => 900,
    'charges' => "1x",
    'premium' => 1,
    'vocations' => ["Druid"],
    'use_vocations' => ["Druid"],
    'icon' => "images/spells/wiki/paralyze.gif",
    'status_icon' => "freezing.gif",
    'effect_pt' => "<img src=\"images/spells/status/freezing.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Congela e reduz drasticamente a <span class=\"effect-ice\">velocidade de movimento</span> do alvo a quase zero.",
    'effect_en' => "<img src=\"images/spells/status/freezing.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Freezes and drastically slows target <span class=\"effect-ice\">movement speed</span> to nearly zero.",
    'effect' => "<img src=\"images/spells/status/freezing.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Congela e reduz drasticamente a <span class=\"effect-ice\">velocidade de movimento</span> do alvo a quase zero.",
  ],
  [
    'id' => 39,
    'name' => "Fire Field",
    'popular_alias' => "",
    'words' => "adevo grav flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 3,
    'use_maglevel' => 1,
    'maglevel_display' => 'Uso: <strong>ML 1</strong><div class="spell-ml-sub">Fazer: ML 3</div>',
    'maglevel_sort' => 1,
    'mana' => 60,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/fire_field.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-fire\">fogo</span> em cruz de 5 sqm com dano por queimadura contínua.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a cross-shaped 5-sqm <span class=\"effect-fire\">fire</span> field inflicting persistent burn damage.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-fire\">fogo</span> em cruz de 5 sqm com dano por queimadura contínua.",
  ],
  [
    'id' => 40,
    'name' => "Fire Wall",
    'popular_alias' => "",
    'words' => "adevo mas grav flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 13,
    'use_maglevel' => 6,
    'maglevel_display' => 'Uso: <strong>ML 6</strong><div class="spell-ml-sub">Fazer: ML 13</div>',
    'maglevel_sort' => 6,
    'mana' => 200,
    'charges' => "4x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/fire_wall.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Muralha de <span class=\"effect-fire\">fogo</span> linear de 5 sqm causando dano severo a quem atravessar.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Linear 5-sqm wall of raging <span class=\"effect-fire\">fire</span> burning creatures passing through.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Muralha de <span class=\"effect-fire\">fogo</span> linear de 5 sqm causando dano severo a quem atravessar.",
  ],
  [
    'id' => 41,
    'name' => "Firebomb",
    'popular_alias' => "",
    'words' => "adevo mas flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 9,
    'use_maglevel' => 5,
    'maglevel_display' => 'Uso: <strong>ML 5</strong><div class="spell-ml-sub">Fazer: ML 9</div>',
    'maglevel_sort' => 5,
    'mana' => 150,
    'charges' => "2x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/firebomb.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma grande área 3x3 (9 sqm) coberta por chamas ardentes de <span class=\"effect-fire\">fogo</span>.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a large 3x3 square (9 sqm) covered in burning <span class=\"effect-fire\">fire</span> fields.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma grande área 3x3 (9 sqm) coberta por chamas ardentes de <span class=\"effect-fire\">fogo</span>.",
  ],
  [
    'id' => 42,
    'name' => "Energy Field",
    'popular_alias' => "",
    'words' => "adevo grav vis",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 5,
    'use_maglevel' => 3,
    'maglevel_display' => 'Uso: <strong>ML 3</strong><div class="spell-ml-sub">Fazer: ML 5</div>',
    'maglevel_sort' => 3,
    'mana' => 80,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/energy_field.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-energy\">energia</span> em 1 sqm que eletrocuta criaturas que passem por ele.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a 1-sqm <span class=\"effect-energy\">energy</span> field electrocuting creatures stepping into it.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-energy\">energia</span> em 1 sqm que eletrocuta criaturas que passem por ele.",
  ],
  [
    'id' => 43,
    'name' => "Energy Wall",
    'popular_alias' => "",
    'words' => "adevo mas grav vis",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 18,
    'use_maglevel' => 9,
    'maglevel_display' => 'Uso: <strong>ML 9</strong><div class="spell-ml-sub">Fazer: ML 18</div>',
    'maglevel_sort' => 9,
    'mana' => 250,
    'charges' => "4x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/energy_wall.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Densa muralha de <span class=\"effect-energy\">energia</span> de 5 sqm com alto dano de eletrocussão.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Dense 5-sqm wall of crackling <span class=\"effect-energy\">energy</span> dealing high shock damage.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Densa muralha de <span class=\"effect-energy\">energia</span> de 5 sqm com alto dano de eletrocussão.",
  ],
  [
    'id' => 44,
    'name' => "Energybomb",
    'popular_alias' => "",
    'words' => "adevo mas vis",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 18,
    'use_maglevel' => 10,
    'maglevel_display' => 'Uso: <strong>ML 10</strong><div class="spell-ml-sub">Fazer: ML 18</div>',
    'maglevel_sort' => 10,
    'mana' => 220,
    'charges' => "2x",
    'premium' => 0,
    'vocations' => ["Sorcerer"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/energybomb.gif",
    'status_icon' => "electrified_energy_18x18.png",
    'effect_pt' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma área 3x3 (9 sqm) com fortes campos de <span class=\"effect-energy\">energia</span> acumulada.",
    'effect_en' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a 3x3 square (9 sqm) with concentrated, hazardous <span class=\"effect-energy\">energy</span> fields.",
    'effect' => "<img src=\"images/spells/status/electrified_energy_18x18.png\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma área 3x3 (9 sqm) com fortes campos de <span class=\"effect-energy\">energia</span> acumulada.",
  ],
  [
    'id' => 45,
    'name' => "Poison Field",
    'popular_alias' => "",
    'words' => "adevo grav pox",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 2,
    'use_maglevel' => 0,
    'maglevel_display' => 'Uso: <strong>ML 0</strong><div class="spell-ml-sub">Fazer: ML 2</div>',
    'maglevel_sort' => 0,
    'mana' => 50,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/poison_field.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-poison\">veneno</span> de 1 sqm que envenena qualquer alvo que o toque.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a 1-sqm <span class=\"effect-poison\">poison</span> field that poisons any creature walking on it.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria um campo de <span class=\"effect-poison\">veneno</span> de 1 sqm que envenena qualquer alvo que o toque.",
  ],
  [
    'id' => 46,
    'name' => "Poison Wall",
    'popular_alias' => "",
    'words' => "adevo mas grav pox",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 11,
    'use_maglevel' => 5,
    'maglevel_display' => 'Uso: <strong>ML 5</strong><div class="spell-ml-sub">Fazer: ML 11</div>',
    'maglevel_sort' => 5,
    'mana' => 160,
    'charges' => "4x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/poison_wall.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma barreira reta de <span class=\"effect-poison\">veneno</span> de 5 sqm causando dano constante.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a straight 5-sqm barrier of <span class=\"effect-poison\">poison</span> dealing constant ticks.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma barreira reta de <span class=\"effect-poison\">veneno</span> de 5 sqm causando dano constante.",
  ],
  [
    'id' => 47,
    'name' => "Poisonbomb",
    'popular_alias' => "",
    'words' => "adevo mas pox",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 8,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 8</div>',
    'maglevel_sort' => 4,
    'mana' => 130,
    'charges' => "2x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/poisonbomb.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma área 3x3 de <span class=\"effect-poison\">veneno</span> concentrado para controle de terreno.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Creates a 3x3 area of concentrated <span class=\"effect-poison\">poison</span> for battleground control.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Cria uma área 3x3 de <span class=\"effect-poison\">veneno</span> concentrado para controle de terreno.",
  ],
  [
    'id' => 48,
    'name' => "Soulfire",
    'popular_alias' => "",
    'words' => "adevo res flam",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 13,
    'use_maglevel' => 7,
    'maglevel_display' => 'Uso: <strong>ML 7</strong><div class="spell-ml-sub">Fazer: ML 13</div>',
    'maglevel_sort' => 7,
    'mana' => 150,
    'charges' => "2x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin"],
    'icon' => "images/spells/wiki/soulfire.gif",
    'status_icon' => "burning.gif",
    'effect_pt' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Incendeia o alvo com <span class=\"effect-fire\">chamas da alma</span> prolongadas que queimam continuamente.",
    'effect_en' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Curses target with soul <span class=\"effect-fire\">fire</span> that burns continuously for a long duration.",
    'effect' => "<img src=\"images/spells/status/burning.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Incendeia o alvo com <span class=\"effect-fire\">chamas da alma</span> prolongadas que queimam continuamente.",
  ],
  [
    'id' => 49,
    'name' => "Envenom",
    'popular_alias' => "",
    'words' => "adevo res pox",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Ataque",
    'group_en' => "Attack Rune",
    'maglevel' => 7,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 7</div>',
    'maglevel_sort' => 4,
    'mana' => 100,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/envenom.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Envenena diretamente um alvo causando dano gradativo de <span class=\"effect-poison\">veneno</span>.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Directly infects a single target with progressive <span class=\"effect-poison\">poison</span> damage.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Envenena diretamente um alvo causando dano gradativo de <span class=\"effect-poison\">veneno</span>.",
  ],
  [
    'id' => 50,
    'name' => "Intense Healing Rune",
    'popular_alias' => "IH",
    'words' => "adura gran",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Cura",
    'group_en' => "Healing Rune",
    'maglevel' => 4,
    'use_maglevel' => 1,
    'maglevel_display' => 'Uso: <strong>ML 1</strong><div class="spell-ml-sub">Fazer: ML 4</div>',
    'maglevel_sort' => 1,
    'mana' => 60,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/intense_healing_rune.gif",
    'status_icon' => "",
    'effect_pt' => "Restaura moderada quantidade de <span class=\"effect-heal\">vida (HP)</span> do alvo.",
    'effect_en' => "Restores a moderate amount of <span class=\"effect-heal\">hit points (HP)</span> of the target.",
    'effect' => "Restaura moderada quantidade de <span class=\"effect-heal\">vida (HP)</span> do alvo.",
  ],
  [
    'id' => 51,
    'name' => "Antidote Rune",
    'popular_alias' => "",
    'words' => "adana pox",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Cura",
    'group_en' => "Healing Rune",
    'maglevel' => 5,
    'use_maglevel' => 0,
    'maglevel_display' => 'Uso: <strong>ML 0</strong><div class="spell-ml-sub">Fazer: ML 5</div>',
    'maglevel_sort' => 0,
    'mana' => 50,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/antidote_rune.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Runa portátil para curar e neutralizar <span class=\"effect-poison\">envenenamento</span> à distância.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Portable rune to cure and neutralize <span class=\"effect-poison\">poisoning</span> from range.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Runa portátil para curar e neutralizar <span class=\"effect-poison\">envenenamento</span> à distância.",
  ],
  [
    'id' => 52,
    'name' => "Destroy Field",
    'popular_alias' => "",
    'words' => "adito grav",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 6,
    'use_maglevel' => 3,
    'maglevel_display' => 'Uso: <strong>ML 3</strong><div class="spell-ml-sub">Fazer: ML 6</div>',
    'maglevel_sort' => 3,
    'mana' => 60,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/destroy_field.gif",
    'status_icon' => "",
    'effect_pt' => "Remove e dissipa campos de fogo, energia ou veneno em 1 sqm à distância.",
    'effect_en' => "Removes and dispels hazardous fields of fire, energy, or poison from 1 tile at range.",
    'effect' => "Remove e dissipa campos de fogo, energia ou veneno em 1 sqm à distância.",
  ],
  [
    'id' => 53,
    'name' => "Desintegrate",
    'popular_alias' => "",
    'words' => "adito tera",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 8,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 8</div>',
    'maglevel_sort' => 4,
    'mana' => 100,
    'charges' => "3x",
    'premium' => 0,
    'vocations' => ["Sorcerer", "Druid", "Paladin"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/desintegrate.gif",
    'status_icon' => "",
    'effect_pt' => "Desintegra e destrói permanentemente corpos ou itens jogados no chão adjacente.",
    'effect_en' => "Completely disintegrates corpses or movable items on adjacent ground.",
    'effect' => "Desintegra e destrói permanentemente corpos ou itens jogados no chão adjacente.",
  ],
  [
    'id' => 54,
    'name' => "Convince Creature",
    'popular_alias' => "",
    'words' => "adeta sio",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 10,
    'use_maglevel' => 5,
    'maglevel_display' => 'Uso: <strong>ML 5</strong><div class="spell-ml-sub">Fazer: ML 10</div>',
    'maglevel_sort' => 5,
    'mana' => 100,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid"],
    'icon' => "images/spells/wiki/convince_creature.gif",
    'status_icon' => "",
    'effect_pt' => "Doma e convence um monstro selvagem a se tornar seu aliado leal.",
    'effect_en' => "Tames and convinces a wild monster to fight as your loyal ally.",
    'effect' => "Doma e convence um monstro selvagem a se tornar seu aliado leal.",
  ],
  [
    'id' => 55,
    'name' => "Chameleon",
    'popular_alias' => "",
    'words' => "adevo ina",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 11,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 11</div>',
    'maglevel_sort' => 4,
    'mana' => 150,
    'charges' => "1x",
    'premium' => 0,
    'vocations' => ["Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/chameleon.gif",
    'status_icon' => "",
    'effect_pt' => "Camufla o conjurador na forma visual de qualquer objeto estático do cenário.",
    'effect_en' => "Camouflages the caster into the visual form of any static object clicked on the floor.",
    'effect' => "Camufla o conjurador na forma visual de qualquer objeto estático do cenário.",
  ],
  [
    'id' => 56,
    'name' => "Animate Dead",
    'popular_alias' => "",
    'words' => "adana mort",
    'type' => "rune",
    'type_label' => 'Runa',
    'group' => "Runa de Suporte",
    'group_en' => "Support Rune",
    'maglevel' => 7,
    'use_maglevel' => 4,
    'maglevel_display' => 'Uso: <strong>ML 4</strong><div class="spell-ml-sub">Fazer: ML 7</div>',
    'maglevel_sort' => 4,
    'mana' => 300,
    'charges' => "1x",
    'premium' => 1,
    'vocations' => ["Sorcerer", "Druid"],
    'use_vocations' => ["Sorcerer", "Druid", "Paladin", "Knight"],
    'icon' => "images/spells/wiki/animate_dead.gif",
    'status_icon' => "",
    'effect_pt' => "Ergue um Esqueleto aliado a partir de um cadáver fresco no chão.",
    'effect_en' => "Raises a loyal allied skeleton from a fresh corpse on the ground.",
    'effect' => "Ergue um Esqueleto aliado a partir de um cadáver fresco no chão.",
  ],
  [
    'id' => 57,
    'name' => "Food",
    'popular_alias' => "",
    'words' => "exevo pan",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 0,
    'maglevel_display' => '<strong>ML 0</strong>',
    'maglevel_sort' => 0,
    'mana' => 30,
    'charges' => "—",
    'premium' => 0,
    'vocations' => ["Druid", "Paladin"],
    'icon' => "images/spells/wiki/create_food.gif",
    'status_icon' => "hungry.gif",
    'effect_pt' => "<img src=\"images/spells/status/hungry.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura diversos alimentos para manter a regeneração de vida e mana ativa.",
    'effect_en' => "<img src=\"images/spells/status/hungry.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjures various foods to keep hit points and mana regeneration active.",
    'effect' => "<img src=\"images/spells/status/hungry.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura diversos alimentos para manter a regeneração de vida e mana ativa.",
  ],
  [
    'id' => 58,
    'name' => "Conjure Arrow",
    'popular_alias' => "",
    'words' => "exevo con",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 2,
    'maglevel_display' => '<strong>ML 2</strong>',
    'maglevel_sort' => 2,
    'mana' => 40,
    'charges' => "30x",
    'premium' => 0,
    'vocations' => ["Paladin"],
    'icon' => "images/spells/wiki/conjure_arrow.gif",
    'status_icon' => "",
    'effect_pt' => "Conjura 30 flechas normais para arco instantaneamente.",
    'effect_en' => "Conjures 30 standard arrows for bows instantly.",
    'effect' => "Conjura 30 flechas normais para arco instantaneamente.",
  ],
  [
    'id' => 59,
    'name' => "Conjure Bolt",
    'popular_alias' => "",
    'words' => "exevo con mort",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 6,
    'maglevel_display' => '<strong>ML 6</strong>',
    'maglevel_sort' => 6,
    'mana' => 70,
    'charges' => "20x",
    'premium' => 0,
    'vocations' => ["Paladin"],
    'icon' => "images/spells/wiki/conjure_bolt.gif",
    'status_icon' => "",
    'effect_pt' => "Conjura 20 virotes pesados (bolts) para uso com besta (Crossbow).",
    'effect_en' => "Conjures 20 heavy bolts for crossbow use.",
    'effect' => "Conjura 20 virotes pesados (bolts) para uso com besta (Crossbow).",
  ],
  [
    'id' => 60,
    'name' => "Poisoned Arrow",
    'popular_alias' => "",
    'words' => "exevo con pox",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 5,
    'maglevel_display' => '<strong>ML 5</strong>',
    'maglevel_sort' => 5,
    'mana' => 70,
    'charges' => "20x",
    'premium' => 0,
    'vocations' => ["Paladin"],
    'icon' => "images/spells/wiki/poisoned_arrow.gif",
    'status_icon' => "poisoned.gif",
    'effect_pt' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura 20 flechas com ponta envenenada que infligem <span class=\"effect-poison\">veneno</span> no alvo.",
    'effect_en' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjures 20 arrows coated with venom inflicting <span class=\"effect-poison\">poison</span> on the target.",
    'effect' => "<img src=\"images/spells/status/poisoned.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura 20 flechas com ponta envenenada que infligem <span class=\"effect-poison\">veneno</span> no alvo.",
  ],
  [
    'id' => 61,
    'name' => "Explosive Arrow",
    'popular_alias' => "",
    'words' => "exevo con flam",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 10,
    'maglevel_display' => '<strong>ML 10</strong>',
    'maglevel_sort' => 10,
    'mana' => 120,
    'charges' => "10x",
    'premium' => 1,
    'vocations' => ["Paladin"],
    'icon' => "images/spells/wiki/explosive_arrow.gif",
    'status_icon' => "physical.gif",
    'effect_pt' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura 10 Burst Arrows com <span class=\"effect-phys\">dano em área circular</span> baseado em Magic Level.",
    'effect_en' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjures 10 Burst Arrows dealing <span class=\"effect-phys\">circular area damage</span> based on Magic Level.",
    'effect' => "<img src=\"images/spells/status/physical.gif\" class=\"status-mini-icon\" alt=\"Status\" /> Conjura 10 Burst Arrows com <span class=\"effect-phys\">dano em área circular</span> baseado em Magic Level.",
  ],
  [
    'id' => 62,
    'name' => "Power Bolt",
    'popular_alias' => "",
    'words' => "exevo con vis",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 14,
    'maglevel_display' => '<strong>ML 14</strong>',
    'maglevel_sort' => 14,
    'mana' => 200,
    'charges' => "2x",
    'premium' => 1,
    'vocations' => ["Royal Paladin"],
    'icon' => "images/spells/wiki/power_bolt.gif",
    'status_icon' => "",
    'effect_pt' => "Conjura 2 poderosos Power Bolts de alto impacto físico para Royal Paladins.",
    'effect_en' => "Conjures 2 lethal Power Bolts dealing massive physical damage for Royal Paladins.",
    'effect' => "Conjura 2 poderosos Power Bolts de alto impacto físico para Royal Paladins.",
  ],
  [
    'id' => 63,
    'name' => "Enchant Staff",
    'popular_alias' => "",
    'words' => "exeta vis",
    'type' => "conjure",
    'type_label' => 'Conjuração',
    'group' => "Conjuração",
    'group_en' => "Conjuration",
    'maglevel' => 22,
    'maglevel_display' => '<strong>ML 22</strong>',
    'maglevel_sort' => 22,
    'mana' => 80,
    'charges' => "1x",
    'premium' => 1,
    'vocations' => ["Master Sorcerer"],
    'icon' => "images/spells/wiki/enchant_staff.gif",
    'status_icon' => "",
    'effect_pt' => "Encanta temporariamente um simples cajado de madeira (Staff) em uma arma mágica.",
    'effect_en' => "Temporarily enchants a simple wooden staff into a magic weapon.",
    'effect' => "Encanta temporariamente um simples cajado de madeira (Staff) em uma arma mágica.",
  ],
];
