<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Ot74.Gameplay.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\tools\map-editor\Ot74.Map.Core\Otbm\*.cs" Link="MapTool\Core\%(Filename)%(Extension)" />
    <Compile Include="..\..\..\tools\map-editor\Ot74.Map.Source\*.cs" Link="MapTool\Source\%(Filename)%(Extension)" />
    <Compile Include="..\..\..\tools\map-editor\Ot74.Map.Items\*.cs" Link="MapTool\Items\%(Filename)%(Extension)" />
    <Compile Include="..\..\..\tools\map-editor\Ot74.Map.Sprites\*.cs" Link="MapTool\Sprites\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
